// Code generated by go-swagger; DO NOT EDIT.

package misc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// QueryBlockTimesReader is a Reader for the QueryBlockTimes structure.
type QueryBlockTimesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QueryBlockTimesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewQueryBlockTimesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewQueryBlockTimesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewQueryBlockTimesOK creates a QueryBlockTimesOK with default headers values
func NewQueryBlockTimesOK() *QueryBlockTimesOK {
	return &QueryBlockTimesOK{}
}

/*QueryBlockTimesOK handles this case with default header values.

OK
*/
type QueryBlockTimesOK struct {
	Payload []int64
}

func (o *QueryBlockTimesOK) Error() string {
	return fmt.Sprintf("[GET /misc/block-times][%d] queryBlockTimesOK  %+v", 200, o.Payload)
}

func (o *QueryBlockTimesOK) GetPayload() []int64 {
	return o.Payload
}

func (o *QueryBlockTimesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQueryBlockTimesInternalServerError creates a QueryBlockTimesInternalServerError with default headers values
func NewQueryBlockTimesInternalServerError() *QueryBlockTimesInternalServerError {
	return &QueryBlockTimesInternalServerError{}
}

/*QueryBlockTimesInternalServerError handles this case with default header values.

Server internal error
*/
type QueryBlockTimesInternalServerError struct {
}

func (o *QueryBlockTimesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /misc/block-times][%d] queryBlockTimesInternalServerError ", 500)
}

func (o *QueryBlockTimesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
