// Code generated by go-swagger; DO NOT EDIT.

package comment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new comment API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for comment API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	FollowupComment(params *FollowupCommentParams) (*FollowupCommentOK, error)

	NewThread(params *NewThreadParams) (*NewThreadOK, error)

	RewardComments(params *RewardCommentsParams) (*RewardCommentsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  FollowupComment posts a follow up comment under some thread
*/
func (a *Client) FollowupComment(params *FollowupCommentParams) (*FollowupCommentOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewFollowupCommentParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "followupComment",
		Method:             "POST",
		PathPattern:        "/comment/followup-comment",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &FollowupCommentReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*FollowupCommentOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for followupComment: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  NewThread posts a new comment to open a new thread
*/
func (a *Client) NewThread(params *NewThreadParams) (*NewThreadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewNewThreadParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "newThread",
		Method:             "POST",
		PathPattern:        "/comment/new-thread",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &NewThreadReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*NewThreadOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for newThread: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  RewardComments rewards some comments with coins
*/
func (a *Client) RewardComments(params *RewardCommentsParams) (*RewardCommentsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRewardCommentsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "rewardComments",
		Method:             "POST",
		PathPattern:        "/comment/reward-comments",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &RewardCommentsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*RewardCommentsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for rewardComments: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
