// Code generated by go-swagger; DO NOT EDIT.

package comment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/coinexchain/dex-api-go/models"
)

// NewThreadReader is a Reader for the NewThread structure.
type NewThreadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NewThreadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNewThreadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNewThreadBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewNewThreadInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNewThreadOK creates a NewThreadOK with default headers values
func NewNewThreadOK() *NewThreadOK {
	return &NewThreadOK{}
}

/*NewThreadOK handles this case with default header values.

Tx was succesfully generated
*/
type NewThreadOK struct {
	Payload *models.StdTx
}

func (o *NewThreadOK) Error() string {
	return fmt.Sprintf("[POST /comment/new-thread][%d] newThreadOK  %+v", 200, o.Payload)
}

func (o *NewThreadOK) GetPayload() *models.StdTx {
	return o.Payload
}

func (o *NewThreadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StdTx)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNewThreadBadRequest creates a NewThreadBadRequest with default headers values
func NewNewThreadBadRequest() *NewThreadBadRequest {
	return &NewThreadBadRequest{}
}

/*NewThreadBadRequest handles this case with default header values.

Invalid request
*/
type NewThreadBadRequest struct {
}

func (o *NewThreadBadRequest) Error() string {
	return fmt.Sprintf("[POST /comment/new-thread][%d] newThreadBadRequest ", 400)
}

func (o *NewThreadBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNewThreadInternalServerError creates a NewThreadInternalServerError with default headers values
func NewNewThreadInternalServerError() *NewThreadInternalServerError {
	return &NewThreadInternalServerError{}
}

/*NewThreadInternalServerError handles this case with default header values.

Server internal error
*/
type NewThreadInternalServerError struct {
}

func (o *NewThreadInternalServerError) Error() string {
	return fmt.Sprintf("[POST /comment/new-thread][%d] newThreadInternalServerError ", 500)
}

func (o *NewThreadInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*NewThreadBody new thread body
swagger:model NewThreadBody
*/
type NewThreadBody struct {

	// base req
	BaseReq *models.BaseReq `json:"base_req,omitempty"`

	// content
	Content string `json:"content,omitempty"`

	// content type
	ContentType int64 `json:"content_type,omitempty"`

	// donation
	Donation string `json:"donation,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this new thread body
func (o *NewThreadBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBaseReq(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *NewThreadBody) validateBaseReq(formats strfmt.Registry) error {

	if swag.IsZero(o.BaseReq) { // not required
		return nil
	}

	if o.BaseReq != nil {
		if err := o.BaseReq.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("newThreadReq" + "." + "base_req")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *NewThreadBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *NewThreadBody) UnmarshalBinary(b []byte) error {
	var res NewThreadBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
