// Code generated by go-swagger; DO NOT EDIT.

package comment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/coinexchain/dex-api-go/models"
)

// QueryCommentReader is a Reader for the QueryComment structure.
type QueryCommentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QueryCommentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewQueryCommentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewQueryCommentInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewQueryCommentOK creates a QueryCommentOK with default headers values
func NewQueryCommentOK() *QueryCommentOK {
	return &QueryCommentOK{}
}

/*QueryCommentOK handles this case with default header values.

OK
*/
type QueryCommentOK struct {
	Payload *QueryCommentOKBody
}

func (o *QueryCommentOK) Error() string {
	return fmt.Sprintf("[GET /comment/comments][%d] queryCommentOK  %+v", 200, o.Payload)
}

func (o *QueryCommentOK) GetPayload() *QueryCommentOKBody {
	return o.Payload
}

func (o *QueryCommentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(QueryCommentOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQueryCommentInternalServerError creates a QueryCommentInternalServerError with default headers values
func NewQueryCommentInternalServerError() *QueryCommentInternalServerError {
	return &QueryCommentInternalServerError{}
}

/*QueryCommentInternalServerError handles this case with default header values.

Server internal error
*/
type QueryCommentInternalServerError struct {
}

func (o *QueryCommentInternalServerError) Error() string {
	return fmt.Sprintf("[GET /comment/comments][%d] queryCommentInternalServerError ", 500)
}

func (o *QueryCommentInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*QueryCommentOKBody query comment o k body
swagger:model QueryCommentOKBody
*/
type QueryCommentOKBody struct {

	// data
	Data []*models.Comment `json:"data"`

	// timesid
	Timesid []int64 `json:"timesid"`
}

// Validate validates this query comment o k body
func (o *QueryCommentOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *QueryCommentOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("queryCommentOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *QueryCommentOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *QueryCommentOKBody) UnmarshalBinary(b []byte) error {
	var res QueryCommentOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
