// Code generated by go-swagger; DO NOT EDIT.

package governance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/coinexchain/dex-api-go/models"
)

// GetVoterByAddrReader is a Reader for the GetVoterByAddr structure.
type GetVoterByAddrReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetVoterByAddrReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetVoterByAddrOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetVoterByAddrBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetVoterByAddrNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetVoterByAddrInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetVoterByAddrOK creates a GetVoterByAddrOK with default headers values
func NewGetVoterByAddrOK() *GetVoterByAddrOK {
	return &GetVoterByAddrOK{}
}

/*GetVoterByAddrOK handles this case with default header values.

OK
*/
type GetVoterByAddrOK struct {
	Payload *GetVoterByAddrOKBody
}

func (o *GetVoterByAddrOK) Error() string {
	return fmt.Sprintf("[GET /gov/proposals/{proposalId}/votes/{voter}][%d] getVoterByAddrOK  %+v", 200, o.Payload)
}

func (o *GetVoterByAddrOK) GetPayload() *GetVoterByAddrOKBody {
	return o.Payload
}

func (o *GetVoterByAddrOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetVoterByAddrOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetVoterByAddrBadRequest creates a GetVoterByAddrBadRequest with default headers values
func NewGetVoterByAddrBadRequest() *GetVoterByAddrBadRequest {
	return &GetVoterByAddrBadRequest{}
}

/*GetVoterByAddrBadRequest handles this case with default header values.

Invalid proposal id or voter address
*/
type GetVoterByAddrBadRequest struct {
}

func (o *GetVoterByAddrBadRequest) Error() string {
	return fmt.Sprintf("[GET /gov/proposals/{proposalId}/votes/{voter}][%d] getVoterByAddrBadRequest ", 400)
}

func (o *GetVoterByAddrBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetVoterByAddrNotFound creates a GetVoterByAddrNotFound with default headers values
func NewGetVoterByAddrNotFound() *GetVoterByAddrNotFound {
	return &GetVoterByAddrNotFound{}
}

/*GetVoterByAddrNotFound handles this case with default header values.

Found no vote
*/
type GetVoterByAddrNotFound struct {
}

func (o *GetVoterByAddrNotFound) Error() string {
	return fmt.Sprintf("[GET /gov/proposals/{proposalId}/votes/{voter}][%d] getVoterByAddrNotFound ", 404)
}

func (o *GetVoterByAddrNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetVoterByAddrInternalServerError creates a GetVoterByAddrInternalServerError with default headers values
func NewGetVoterByAddrInternalServerError() *GetVoterByAddrInternalServerError {
	return &GetVoterByAddrInternalServerError{}
}

/*GetVoterByAddrInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetVoterByAddrInternalServerError struct {
}

func (o *GetVoterByAddrInternalServerError) Error() string {
	return fmt.Sprintf("[GET /gov/proposals/{proposalId}/votes/{voter}][%d] getVoterByAddrInternalServerError ", 500)
}

func (o *GetVoterByAddrInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetVoterByAddrOKBody get voter by addr o k body
swagger:model GetVoterByAddrOKBody
*/
type GetVoterByAddrOKBody struct {

	// height
	Height string `json:"height,omitempty"`

	// result
	Result *models.Vote `json:"result,omitempty"`
}

// Validate validates this get voter by addr o k body
func (o *GetVoterByAddrOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetVoterByAddrOKBody) validateResult(formats strfmt.Registry) error {

	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getVoterByAddrOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetVoterByAddrOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetVoterByAddrOKBody) UnmarshalBinary(b []byte) error {
	var res GetVoterByAddrOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
