// Code generated by go-swagger; DO NOT EDIT.

package governance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetVotingParametersParams creates a new GetVotingParametersParams object
// with the default values initialized.
func NewGetVotingParametersParams() *GetVotingParametersParams {

	return &GetVotingParametersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetVotingParametersParamsWithTimeout creates a new GetVotingParametersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetVotingParametersParamsWithTimeout(timeout time.Duration) *GetVotingParametersParams {

	return &GetVotingParametersParams{

		timeout: timeout,
	}
}

// NewGetVotingParametersParamsWithContext creates a new GetVotingParametersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetVotingParametersParamsWithContext(ctx context.Context) *GetVotingParametersParams {

	return &GetVotingParametersParams{

		Context: ctx,
	}
}

// NewGetVotingParametersParamsWithHTTPClient creates a new GetVotingParametersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetVotingParametersParamsWithHTTPClient(client *http.Client) *GetVotingParametersParams {

	return &GetVotingParametersParams{
		HTTPClient: client,
	}
}

/*GetVotingParametersParams contains all the parameters to send to the API endpoint
for the get voting parameters operation typically these are written to a http.Request
*/
type GetVotingParametersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get voting parameters params
func (o *GetVotingParametersParams) WithTimeout(timeout time.Duration) *GetVotingParametersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get voting parameters params
func (o *GetVotingParametersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get voting parameters params
func (o *GetVotingParametersParams) WithContext(ctx context.Context) *GetVotingParametersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get voting parameters params
func (o *GetVotingParametersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get voting parameters params
func (o *GetVotingParametersParams) WithHTTPClient(client *http.Client) *GetVotingParametersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get voting parameters params
func (o *GetVotingParametersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetVotingParametersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
