// Code generated by go-swagger; DO NOT EDIT.

package governance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/coinexchain/dex-api-go/models"
)

// GetVotersReader is a Reader for the GetVoters structure.
type GetVotersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetVotersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetVotersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetVotersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetVotersInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetVotersOK creates a GetVotersOK with default headers values
func NewGetVotersOK() *GetVotersOK {
	return &GetVotersOK{}
}

/*GetVotersOK handles this case with default header values.

OK
*/
type GetVotersOK struct {
	Payload *GetVotersOKBody
}

func (o *GetVotersOK) Error() string {
	return fmt.Sprintf("[GET /gov/proposals/{proposalId}/votes][%d] getVotersOK  %+v", 200, o.Payload)
}

func (o *GetVotersOK) GetPayload() *GetVotersOKBody {
	return o.Payload
}

func (o *GetVotersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetVotersOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetVotersBadRequest creates a GetVotersBadRequest with default headers values
func NewGetVotersBadRequest() *GetVotersBadRequest {
	return &GetVotersBadRequest{}
}

/*GetVotersBadRequest handles this case with default header values.

Invalid proposal id
*/
type GetVotersBadRequest struct {
}

func (o *GetVotersBadRequest) Error() string {
	return fmt.Sprintf("[GET /gov/proposals/{proposalId}/votes][%d] getVotersBadRequest ", 400)
}

func (o *GetVotersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetVotersInternalServerError creates a GetVotersInternalServerError with default headers values
func NewGetVotersInternalServerError() *GetVotersInternalServerError {
	return &GetVotersInternalServerError{}
}

/*GetVotersInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetVotersInternalServerError struct {
}

func (o *GetVotersInternalServerError) Error() string {
	return fmt.Sprintf("[GET /gov/proposals/{proposalId}/votes][%d] getVotersInternalServerError ", 500)
}

func (o *GetVotersInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetVotersOKBody get voters o k body
swagger:model GetVotersOKBody
*/
type GetVotersOKBody struct {

	// height
	Height string `json:"height,omitempty"`

	// result
	Result []*models.Vote `json:"result"`
}

// Validate validates this get voters o k body
func (o *GetVotersOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetVotersOKBody) validateResult(formats strfmt.Registry) error {

	if swag.IsZero(o.Result) { // not required
		return nil
	}

	for i := 0; i < len(o.Result); i++ {
		if swag.IsZero(o.Result[i]) { // not required
			continue
		}

		if o.Result[i] != nil {
			if err := o.Result[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getVotersOK" + "." + "result" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetVotersOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetVotersOKBody) UnmarshalBinary(b []byte) error {
	var res GetVotersOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
