// Code generated by go-swagger; DO NOT EDIT.

package governance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/coinexchain/dex-api-go/models"
)

// GetProposalsReader is a Reader for the GetProposals structure.
type GetProposalsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProposalsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProposalsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetProposalsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetProposalsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetProposalsOK creates a GetProposalsOK with default headers values
func NewGetProposalsOK() *GetProposalsOK {
	return &GetProposalsOK{}
}

/*GetProposalsOK handles this case with default header values.

OK
*/
type GetProposalsOK struct {
	Payload *GetProposalsOKBody
}

func (o *GetProposalsOK) Error() string {
	return fmt.Sprintf("[GET /gov/proposals][%d] getProposalsOK  %+v", 200, o.Payload)
}

func (o *GetProposalsOK) GetPayload() *GetProposalsOKBody {
	return o.Payload
}

func (o *GetProposalsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetProposalsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProposalsBadRequest creates a GetProposalsBadRequest with default headers values
func NewGetProposalsBadRequest() *GetProposalsBadRequest {
	return &GetProposalsBadRequest{}
}

/*GetProposalsBadRequest handles this case with default header values.

Invalid query parameters
*/
type GetProposalsBadRequest struct {
}

func (o *GetProposalsBadRequest) Error() string {
	return fmt.Sprintf("[GET /gov/proposals][%d] getProposalsBadRequest ", 400)
}

func (o *GetProposalsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetProposalsInternalServerError creates a GetProposalsInternalServerError with default headers values
func NewGetProposalsInternalServerError() *GetProposalsInternalServerError {
	return &GetProposalsInternalServerError{}
}

/*GetProposalsInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetProposalsInternalServerError struct {
}

func (o *GetProposalsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /gov/proposals][%d] getProposalsInternalServerError ", 500)
}

func (o *GetProposalsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetProposalsOKBody get proposals o k body
swagger:model GetProposalsOKBody
*/
type GetProposalsOKBody struct {

	// height
	Height string `json:"height,omitempty"`

	// result
	Result []*models.TextProposal `json:"result"`
}

// Validate validates this get proposals o k body
func (o *GetProposalsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetProposalsOKBody) validateResult(formats strfmt.Registry) error {

	if swag.IsZero(o.Result) { // not required
		return nil
	}

	for i := 0; i < len(o.Result); i++ {
		if swag.IsZero(o.Result[i]) { // not required
			continue
		}

		if o.Result[i] != nil {
			if err := o.Result[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getProposalsOK" + "." + "result" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetProposalsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetProposalsOKBody) UnmarshalBinary(b []byte) error {
	var res GetProposalsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
