// Code generated by go-swagger; DO NOT EDIT.

package governance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSubmitProposalParams creates a new SubmitProposalParams object
// with the default values initialized.
func NewSubmitProposalParams() *SubmitProposalParams {
	var ()
	return &SubmitProposalParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSubmitProposalParamsWithTimeout creates a new SubmitProposalParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSubmitProposalParamsWithTimeout(timeout time.Duration) *SubmitProposalParams {
	var ()
	return &SubmitProposalParams{

		timeout: timeout,
	}
}

// NewSubmitProposalParamsWithContext creates a new SubmitProposalParams object
// with the default values initialized, and the ability to set a context for a request
func NewSubmitProposalParamsWithContext(ctx context.Context) *SubmitProposalParams {
	var ()
	return &SubmitProposalParams{

		Context: ctx,
	}
}

// NewSubmitProposalParamsWithHTTPClient creates a new SubmitProposalParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSubmitProposalParamsWithHTTPClient(client *http.Client) *SubmitProposalParams {
	var ()
	return &SubmitProposalParams{
		HTTPClient: client,
	}
}

/*SubmitProposalParams contains all the parameters to send to the API endpoint
for the submit proposal operation typically these are written to a http.Request
*/
type SubmitProposalParams struct {

	/*PostProposalBody
	  valid value of `"proposal_type"` can be `"text"`, `"parameter_change"`, `"software_upgrade"`

	*/
	PostProposalBody SubmitProposalBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the submit proposal params
func (o *SubmitProposalParams) WithTimeout(timeout time.Duration) *SubmitProposalParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the submit proposal params
func (o *SubmitProposalParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the submit proposal params
func (o *SubmitProposalParams) WithContext(ctx context.Context) *SubmitProposalParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the submit proposal params
func (o *SubmitProposalParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the submit proposal params
func (o *SubmitProposalParams) WithHTTPClient(client *http.Client) *SubmitProposalParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the submit proposal params
func (o *SubmitProposalParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPostProposalBody adds the postProposalBody to the submit proposal params
func (o *SubmitProposalParams) WithPostProposalBody(postProposalBody SubmitProposalBody) *SubmitProposalParams {
	o.SetPostProposalBody(postProposalBody)
	return o
}

// SetPostProposalBody adds the postProposalBody to the submit proposal params
func (o *SubmitProposalParams) SetPostProposalBody(postProposalBody SubmitProposalBody) {
	o.PostProposalBody = postProposalBody
}

// WriteToRequest writes these params to a swagger request
func (o *SubmitProposalParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.PostProposalBody); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
