// Code generated by go-swagger; DO NOT EDIT.

package governance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSubmitParameterChangeProposalParams creates a new SubmitParameterChangeProposalParams object
// with the default values initialized.
func NewSubmitParameterChangeProposalParams() *SubmitParameterChangeProposalParams {
	var ()
	return &SubmitParameterChangeProposalParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSubmitParameterChangeProposalParamsWithTimeout creates a new SubmitParameterChangeProposalParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSubmitParameterChangeProposalParamsWithTimeout(timeout time.Duration) *SubmitParameterChangeProposalParams {
	var ()
	return &SubmitParameterChangeProposalParams{

		timeout: timeout,
	}
}

// NewSubmitParameterChangeProposalParamsWithContext creates a new SubmitParameterChangeProposalParams object
// with the default values initialized, and the ability to set a context for a request
func NewSubmitParameterChangeProposalParamsWithContext(ctx context.Context) *SubmitParameterChangeProposalParams {
	var ()
	return &SubmitParameterChangeProposalParams{

		Context: ctx,
	}
}

// NewSubmitParameterChangeProposalParamsWithHTTPClient creates a new SubmitParameterChangeProposalParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSubmitParameterChangeProposalParamsWithHTTPClient(client *http.Client) *SubmitParameterChangeProposalParams {
	var ()
	return &SubmitParameterChangeProposalParams{
		HTTPClient: client,
	}
}

/*SubmitParameterChangeProposalParams contains all the parameters to send to the API endpoint
for the submit parameter change proposal operation typically these are written to a http.Request
*/
type SubmitParameterChangeProposalParams struct {

	/*PostProposalBody
	  The parameter change proposal body that contains all parameter changes

	*/
	PostProposalBody SubmitParameterChangeProposalBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the submit parameter change proposal params
func (o *SubmitParameterChangeProposalParams) WithTimeout(timeout time.Duration) *SubmitParameterChangeProposalParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the submit parameter change proposal params
func (o *SubmitParameterChangeProposalParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the submit parameter change proposal params
func (o *SubmitParameterChangeProposalParams) WithContext(ctx context.Context) *SubmitParameterChangeProposalParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the submit parameter change proposal params
func (o *SubmitParameterChangeProposalParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the submit parameter change proposal params
func (o *SubmitParameterChangeProposalParams) WithHTTPClient(client *http.Client) *SubmitParameterChangeProposalParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the submit parameter change proposal params
func (o *SubmitParameterChangeProposalParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPostProposalBody adds the postProposalBody to the submit parameter change proposal params
func (o *SubmitParameterChangeProposalParams) WithPostProposalBody(postProposalBody SubmitParameterChangeProposalBody) *SubmitParameterChangeProposalParams {
	o.SetPostProposalBody(postProposalBody)
	return o
}

// SetPostProposalBody adds the postProposalBody to the submit parameter change proposal params
func (o *SubmitParameterChangeProposalParams) SetPostProposalBody(postProposalBody SubmitParameterChangeProposalBody) {
	o.PostProposalBody = postProposalBody
}

// WriteToRequest writes these params to a swagger request
func (o *SubmitParameterChangeProposalParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.PostProposalBody); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
