// Code generated by go-swagger; DO NOT EDIT.

package tx

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new tx API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for tx API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetTxFromTradeServer(params *GetTxFromTradeServerParams) (*GetTxFromTradeServerOK, error)

	QueryIncome(params *QueryIncomeParams) (*QueryIncomeOK, error)

	QueryTx(params *QueryTxParams) (*QueryTxOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetTxFromTradeServer gets a tx from trade server by hash
*/
func (a *Client) GetTxFromTradeServer(params *GetTxFromTradeServerParams) (*GetTxFromTradeServerOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetTxFromTradeServerParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getTxFromTradeServer",
		Method:             "GET",
		PathPattern:        "/tx/txs/{hash}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetTxFromTradeServerReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetTxFromTradeServerOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getTxFromTradeServer: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  QueryIncome queries account all income until to given time

  Query income info
*/
func (a *Client) QueryIncome(params *QueryIncomeParams) (*QueryIncomeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewQueryIncomeParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "queryIncome",
		Method:             "GET",
		PathPattern:        "/tx/incomes",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &QueryIncomeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*QueryIncomeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for queryIncome: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  QueryTx queries transactions

  Query transactions signed by given account until to given time
*/
func (a *Client) QueryTx(params *QueryTxParams) (*QueryTxOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewQueryTxParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "queryTx",
		Method:             "GET",
		PathPattern:        "/tx/txs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &QueryTxReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*QueryTxOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for queryTx: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
