// Code generated by go-swagger; DO NOT EDIT.

package distribution

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/coinexchain/dex-api-go/models"
)

// DonateToCommunityPoolReader is a Reader for the DonateToCommunityPool structure.
type DonateToCommunityPoolReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DonateToCommunityPoolReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDonateToCommunityPoolOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDonateToCommunityPoolBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDonateToCommunityPoolInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDonateToCommunityPoolOK creates a DonateToCommunityPoolOK with default headers values
func NewDonateToCommunityPoolOK() *DonateToCommunityPoolOK {
	return &DonateToCommunityPoolOK{}
}

/*DonateToCommunityPoolOK handles this case with default header values.

Donate tx result
*/
type DonateToCommunityPoolOK struct {
	Payload *models.StdTx
}

func (o *DonateToCommunityPoolOK) Error() string {
	return fmt.Sprintf("[POST /distribution/{accAddress}/donates][%d] donateToCommunityPoolOK  %+v", 200, o.Payload)
}

func (o *DonateToCommunityPoolOK) GetPayload() *models.StdTx {
	return o.Payload
}

func (o *DonateToCommunityPoolOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StdTx)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDonateToCommunityPoolBadRequest creates a DonateToCommunityPoolBadRequest with default headers values
func NewDonateToCommunityPoolBadRequest() *DonateToCommunityPoolBadRequest {
	return &DonateToCommunityPoolBadRequest{}
}

/*DonateToCommunityPoolBadRequest handles this case with default header values.

Invalid Request
*/
type DonateToCommunityPoolBadRequest struct {
}

func (o *DonateToCommunityPoolBadRequest) Error() string {
	return fmt.Sprintf("[POST /distribution/{accAddress}/donates][%d] donateToCommunityPoolBadRequest ", 400)
}

func (o *DonateToCommunityPoolBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDonateToCommunityPoolInternalServerError creates a DonateToCommunityPoolInternalServerError with default headers values
func NewDonateToCommunityPoolInternalServerError() *DonateToCommunityPoolInternalServerError {
	return &DonateToCommunityPoolInternalServerError{}
}

/*DonateToCommunityPoolInternalServerError handles this case with default header values.

Internal Server Error
*/
type DonateToCommunityPoolInternalServerError struct {
}

func (o *DonateToCommunityPoolInternalServerError) Error() string {
	return fmt.Sprintf("[POST /distribution/{accAddress}/donates][%d] donateToCommunityPoolInternalServerError ", 500)
}

func (o *DonateToCommunityPoolInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*DonateToCommunityPoolBody donate to community pool body
swagger:model DonateToCommunityPoolBody
*/
type DonateToCommunityPoolBody struct {

	// amount
	Amount []*models.Coin `json:"amount"`

	// base req
	BaseReq *models.BaseReq `json:"base_req,omitempty"`
}

// Validate validates this donate to community pool body
func (o *DonateToCommunityPoolBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateBaseReq(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DonateToCommunityPoolBody) validateAmount(formats strfmt.Registry) error {

	if swag.IsZero(o.Amount) { // not required
		return nil
	}

	for i := 0; i < len(o.Amount); i++ {
		if swag.IsZero(o.Amount[i]) { // not required
			continue
		}

		if o.Amount[i] != nil {
			if err := o.Amount[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("amount" + "." + "amount" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *DonateToCommunityPoolBody) validateBaseReq(formats strfmt.Registry) error {

	if swag.IsZero(o.BaseReq) { // not required
		return nil
	}

	if o.BaseReq != nil {
		if err := o.BaseReq.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("amount" + "." + "base_req")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DonateToCommunityPoolBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DonateToCommunityPoolBody) UnmarshalBinary(b []byte) error {
	var res DonateToCommunityPoolBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
