// Code generated by go-swagger; DO NOT EDIT.

package distribution

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/coinexchain/dex-api-go/models"
)

// GetOutstandingRewardsReader is a Reader for the GetOutstandingRewards structure.
type GetOutstandingRewardsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOutstandingRewardsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOutstandingRewardsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetOutstandingRewardsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetOutstandingRewardsOK creates a GetOutstandingRewardsOK with default headers values
func NewGetOutstandingRewardsOK() *GetOutstandingRewardsOK {
	return &GetOutstandingRewardsOK{}
}

/*GetOutstandingRewardsOK handles this case with default header values.

OK
*/
type GetOutstandingRewardsOK struct {
	Payload *GetOutstandingRewardsOKBody
}

func (o *GetOutstandingRewardsOK) Error() string {
	return fmt.Sprintf("[GET /distribution/validators/{validatorAddr}/outstanding_rewards][%d] getOutstandingRewardsOK  %+v", 200, o.Payload)
}

func (o *GetOutstandingRewardsOK) GetPayload() *GetOutstandingRewardsOKBody {
	return o.Payload
}

func (o *GetOutstandingRewardsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetOutstandingRewardsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOutstandingRewardsInternalServerError creates a GetOutstandingRewardsInternalServerError with default headers values
func NewGetOutstandingRewardsInternalServerError() *GetOutstandingRewardsInternalServerError {
	return &GetOutstandingRewardsInternalServerError{}
}

/*GetOutstandingRewardsInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetOutstandingRewardsInternalServerError struct {
}

func (o *GetOutstandingRewardsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /distribution/validators/{validatorAddr}/outstanding_rewards][%d] getOutstandingRewardsInternalServerError ", 500)
}

func (o *GetOutstandingRewardsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetOutstandingRewardsOKBody get outstanding rewards o k body
swagger:model GetOutstandingRewardsOKBody
*/
type GetOutstandingRewardsOKBody struct {

	// height
	Height string `json:"height,omitempty"`

	// result
	Result []*models.Coin `json:"result"`
}

// Validate validates this get outstanding rewards o k body
func (o *GetOutstandingRewardsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetOutstandingRewardsOKBody) validateResult(formats strfmt.Registry) error {

	if swag.IsZero(o.Result) { // not required
		return nil
	}

	for i := 0; i < len(o.Result); i++ {
		if swag.IsZero(o.Result[i]) { // not required
			continue
		}

		if o.Result[i] != nil {
			if err := o.Result[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getOutstandingRewardsOK" + "." + "result" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetOutstandingRewardsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetOutstandingRewardsOKBody) UnmarshalBinary(b []byte) error {
	var res GetOutstandingRewardsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
