// Code generated by go-swagger; DO NOT EDIT.

package distribution

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllRewardsParams creates a new GetAllRewardsParams object
// with the default values initialized.
func NewGetAllRewardsParams() *GetAllRewardsParams {
	var ()
	return &GetAllRewardsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllRewardsParamsWithTimeout creates a new GetAllRewardsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAllRewardsParamsWithTimeout(timeout time.Duration) *GetAllRewardsParams {
	var ()
	return &GetAllRewardsParams{

		timeout: timeout,
	}
}

// NewGetAllRewardsParamsWithContext creates a new GetAllRewardsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAllRewardsParamsWithContext(ctx context.Context) *GetAllRewardsParams {
	var ()
	return &GetAllRewardsParams{

		Context: ctx,
	}
}

// NewGetAllRewardsParamsWithHTTPClient creates a new GetAllRewardsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAllRewardsParamsWithHTTPClient(client *http.Client) *GetAllRewardsParams {
	var ()
	return &GetAllRewardsParams{
		HTTPClient: client,
	}
}

/*GetAllRewardsParams contains all the parameters to send to the API endpoint
for the get all rewards operation typically these are written to a http.Request
*/
type GetAllRewardsParams struct {

	/*DelegatorAddr
	  Bech32 AccAddress of Delegator

	*/
	DelegatorAddr string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all rewards params
func (o *GetAllRewardsParams) WithTimeout(timeout time.Duration) *GetAllRewardsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all rewards params
func (o *GetAllRewardsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all rewards params
func (o *GetAllRewardsParams) WithContext(ctx context.Context) *GetAllRewardsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all rewards params
func (o *GetAllRewardsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all rewards params
func (o *GetAllRewardsParams) WithHTTPClient(client *http.Client) *GetAllRewardsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all rewards params
func (o *GetAllRewardsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDelegatorAddr adds the delegatorAddr to the get all rewards params
func (o *GetAllRewardsParams) WithDelegatorAddr(delegatorAddr string) *GetAllRewardsParams {
	o.SetDelegatorAddr(delegatorAddr)
	return o
}

// SetDelegatorAddr adds the delegatorAddr to the get all rewards params
func (o *GetAllRewardsParams) SetDelegatorAddr(delegatorAddr string) {
	o.DelegatorAddr = delegatorAddr
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllRewardsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param delegatorAddr
	if err := r.SetPathParam("delegatorAddr", o.DelegatorAddr); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
