// Code generated by go-swagger; DO NOT EDIT.

package distribution

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetWithdrawAddressParams creates a new GetWithdrawAddressParams object
// with the default values initialized.
func NewGetWithdrawAddressParams() *GetWithdrawAddressParams {
	var ()
	return &GetWithdrawAddressParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWithdrawAddressParamsWithTimeout creates a new GetWithdrawAddressParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWithdrawAddressParamsWithTimeout(timeout time.Duration) *GetWithdrawAddressParams {
	var ()
	return &GetWithdrawAddressParams{

		timeout: timeout,
	}
}

// NewGetWithdrawAddressParamsWithContext creates a new GetWithdrawAddressParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetWithdrawAddressParamsWithContext(ctx context.Context) *GetWithdrawAddressParams {
	var ()
	return &GetWithdrawAddressParams{

		Context: ctx,
	}
}

// NewGetWithdrawAddressParamsWithHTTPClient creates a new GetWithdrawAddressParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetWithdrawAddressParamsWithHTTPClient(client *http.Client) *GetWithdrawAddressParams {
	var ()
	return &GetWithdrawAddressParams{
		HTTPClient: client,
	}
}

/*GetWithdrawAddressParams contains all the parameters to send to the API endpoint
for the get withdraw address operation typically these are written to a http.Request
*/
type GetWithdrawAddressParams struct {

	/*DelegatorAddr
	  Bech32 AccAddress of Delegator

	*/
	DelegatorAddr string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get withdraw address params
func (o *GetWithdrawAddressParams) WithTimeout(timeout time.Duration) *GetWithdrawAddressParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get withdraw address params
func (o *GetWithdrawAddressParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get withdraw address params
func (o *GetWithdrawAddressParams) WithContext(ctx context.Context) *GetWithdrawAddressParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get withdraw address params
func (o *GetWithdrawAddressParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get withdraw address params
func (o *GetWithdrawAddressParams) WithHTTPClient(client *http.Client) *GetWithdrawAddressParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get withdraw address params
func (o *GetWithdrawAddressParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDelegatorAddr adds the delegatorAddr to the get withdraw address params
func (o *GetWithdrawAddressParams) WithDelegatorAddr(delegatorAddr string) *GetWithdrawAddressParams {
	o.SetDelegatorAddr(delegatorAddr)
	return o
}

// SetDelegatorAddr adds the delegatorAddr to the get withdraw address params
func (o *GetWithdrawAddressParams) SetDelegatorAddr(delegatorAddr string) {
	o.DelegatorAddr = delegatorAddr
}

// WriteToRequest writes these params to a swagger request
func (o *GetWithdrawAddressParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param delegatorAddr
	if err := r.SetPathParam("delegatorAddr", o.DelegatorAddr); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
