// Code generated by go-swagger; DO NOT EDIT.

package distribution

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetDistributionParamsReader is a Reader for the GetDistributionParams structure.
type GetDistributionParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDistributionParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDistributionParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetDistributionParamsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDistributionParamsOK creates a GetDistributionParamsOK with default headers values
func NewGetDistributionParamsOK() *GetDistributionParamsOK {
	return &GetDistributionParamsOK{}
}

/*GetDistributionParamsOK handles this case with default header values.

OK
*/
type GetDistributionParamsOK struct {
	Payload *GetDistributionParamsOKBody
}

func (o *GetDistributionParamsOK) Error() string {
	return fmt.Sprintf("[GET /distribution/parameters][%d] getDistributionParamsOK  %+v", 200, o.Payload)
}

func (o *GetDistributionParamsOK) GetPayload() *GetDistributionParamsOKBody {
	return o.Payload
}

func (o *GetDistributionParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetDistributionParamsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDistributionParamsInternalServerError creates a GetDistributionParamsInternalServerError with default headers values
func NewGetDistributionParamsInternalServerError() *GetDistributionParamsInternalServerError {
	return &GetDistributionParamsInternalServerError{}
}

/*GetDistributionParamsInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetDistributionParamsInternalServerError struct {
}

func (o *GetDistributionParamsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /distribution/parameters][%d] getDistributionParamsInternalServerError ", 500)
}

func (o *GetDistributionParamsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetDistributionParamsOKBody get distribution params o k body
swagger:model GetDistributionParamsOKBody
*/
type GetDistributionParamsOKBody struct {

	// height
	Height string `json:"height,omitempty"`

	// result
	Result *GetDistributionParamsOKBodyResult `json:"result,omitempty"`
}

// Validate validates this get distribution params o k body
func (o *GetDistributionParamsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetDistributionParamsOKBody) validateResult(formats strfmt.Registry) error {

	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getDistributionParamsOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetDistributionParamsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetDistributionParamsOKBody) UnmarshalBinary(b []byte) error {
	var res GetDistributionParamsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetDistributionParamsOKBodyResult get distribution params o k body result
swagger:model GetDistributionParamsOKBodyResult
*/
type GetDistributionParamsOKBodyResult struct {

	// base proposer reward
	BaseProposerReward string `json:"base_proposer_reward,omitempty"`

	// bonus proposer reward
	BonusProposerReward string `json:"bonus_proposer_reward,omitempty"`

	// community tax
	CommunityTax string `json:"community_tax,omitempty"`
}

// Validate validates this get distribution params o k body result
func (o *GetDistributionParamsOKBodyResult) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetDistributionParamsOKBodyResult) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetDistributionParamsOKBodyResult) UnmarshalBinary(b []byte) error {
	var res GetDistributionParamsOKBodyResult
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
