// Code generated by go-swagger; DO NOT EDIT.

package distribution

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/coinexchain/dex-api-go/models"
)

// WithdrawRewardsByValidatorReader is a Reader for the WithdrawRewardsByValidator structure.
type WithdrawRewardsByValidatorReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WithdrawRewardsByValidatorReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWithdrawRewardsByValidatorOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewWithdrawRewardsByValidatorBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewWithdrawRewardsByValidatorUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewWithdrawRewardsByValidatorInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewWithdrawRewardsByValidatorOK creates a WithdrawRewardsByValidatorOK with default headers values
func NewWithdrawRewardsByValidatorOK() *WithdrawRewardsByValidatorOK {
	return &WithdrawRewardsByValidatorOK{}
}

/*WithdrawRewardsByValidatorOK handles this case with default header values.

OK
*/
type WithdrawRewardsByValidatorOK struct {
	Payload *models.BroadcastTxCommitResult
}

func (o *WithdrawRewardsByValidatorOK) Error() string {
	return fmt.Sprintf("[POST /distribution/delegators/{delegatorAddr}/rewards/{validatorAddr}][%d] withdrawRewardsByValidatorOK  %+v", 200, o.Payload)
}

func (o *WithdrawRewardsByValidatorOK) GetPayload() *models.BroadcastTxCommitResult {
	return o.Payload
}

func (o *WithdrawRewardsByValidatorOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BroadcastTxCommitResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWithdrawRewardsByValidatorBadRequest creates a WithdrawRewardsByValidatorBadRequest with default headers values
func NewWithdrawRewardsByValidatorBadRequest() *WithdrawRewardsByValidatorBadRequest {
	return &WithdrawRewardsByValidatorBadRequest{}
}

/*WithdrawRewardsByValidatorBadRequest handles this case with default header values.

Invalid delegator address or delegation body
*/
type WithdrawRewardsByValidatorBadRequest struct {
}

func (o *WithdrawRewardsByValidatorBadRequest) Error() string {
	return fmt.Sprintf("[POST /distribution/delegators/{delegatorAddr}/rewards/{validatorAddr}][%d] withdrawRewardsByValidatorBadRequest ", 400)
}

func (o *WithdrawRewardsByValidatorBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewWithdrawRewardsByValidatorUnauthorized creates a WithdrawRewardsByValidatorUnauthorized with default headers values
func NewWithdrawRewardsByValidatorUnauthorized() *WithdrawRewardsByValidatorUnauthorized {
	return &WithdrawRewardsByValidatorUnauthorized{}
}

/*WithdrawRewardsByValidatorUnauthorized handles this case with default header values.

Key password is wrong
*/
type WithdrawRewardsByValidatorUnauthorized struct {
}

func (o *WithdrawRewardsByValidatorUnauthorized) Error() string {
	return fmt.Sprintf("[POST /distribution/delegators/{delegatorAddr}/rewards/{validatorAddr}][%d] withdrawRewardsByValidatorUnauthorized ", 401)
}

func (o *WithdrawRewardsByValidatorUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewWithdrawRewardsByValidatorInternalServerError creates a WithdrawRewardsByValidatorInternalServerError with default headers values
func NewWithdrawRewardsByValidatorInternalServerError() *WithdrawRewardsByValidatorInternalServerError {
	return &WithdrawRewardsByValidatorInternalServerError{}
}

/*WithdrawRewardsByValidatorInternalServerError handles this case with default header values.

Internal Server Error
*/
type WithdrawRewardsByValidatorInternalServerError struct {
}

func (o *WithdrawRewardsByValidatorInternalServerError) Error() string {
	return fmt.Sprintf("[POST /distribution/delegators/{delegatorAddr}/rewards/{validatorAddr}][%d] withdrawRewardsByValidatorInternalServerError ", 500)
}

func (o *WithdrawRewardsByValidatorInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*WithdrawRewardsByValidatorBody withdraw rewards by validator body
swagger:model WithdrawRewardsByValidatorBody
*/
type WithdrawRewardsByValidatorBody struct {

	// base req
	BaseReq *models.BaseReq `json:"base_req,omitempty"`
}

// Validate validates this withdraw rewards by validator body
func (o *WithdrawRewardsByValidatorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBaseReq(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *WithdrawRewardsByValidatorBody) validateBaseReq(formats strfmt.Registry) error {

	if swag.IsZero(o.BaseReq) { // not required
		return nil
	}

	if o.BaseReq != nil {
		if err := o.BaseReq.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Withdraw request body" + "." + "base_req")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *WithdrawRewardsByValidatorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *WithdrawRewardsByValidatorBody) UnmarshalBinary(b []byte) error {
	var res WithdrawRewardsByValidatorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
