// Code generated by go-swagger; DO NOT EDIT.

package distribution

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewWithdrawRewardsByValidatorParams creates a new WithdrawRewardsByValidatorParams object
// with the default values initialized.
func NewWithdrawRewardsByValidatorParams() *WithdrawRewardsByValidatorParams {
	var ()
	return &WithdrawRewardsByValidatorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewWithdrawRewardsByValidatorParamsWithTimeout creates a new WithdrawRewardsByValidatorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewWithdrawRewardsByValidatorParamsWithTimeout(timeout time.Duration) *WithdrawRewardsByValidatorParams {
	var ()
	return &WithdrawRewardsByValidatorParams{

		timeout: timeout,
	}
}

// NewWithdrawRewardsByValidatorParamsWithContext creates a new WithdrawRewardsByValidatorParams object
// with the default values initialized, and the ability to set a context for a request
func NewWithdrawRewardsByValidatorParamsWithContext(ctx context.Context) *WithdrawRewardsByValidatorParams {
	var ()
	return &WithdrawRewardsByValidatorParams{

		Context: ctx,
	}
}

// NewWithdrawRewardsByValidatorParamsWithHTTPClient creates a new WithdrawRewardsByValidatorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewWithdrawRewardsByValidatorParamsWithHTTPClient(client *http.Client) *WithdrawRewardsByValidatorParams {
	var ()
	return &WithdrawRewardsByValidatorParams{
		HTTPClient: client,
	}
}

/*WithdrawRewardsByValidatorParams contains all the parameters to send to the API endpoint
for the withdraw rewards by validator operation typically these are written to a http.Request
*/
type WithdrawRewardsByValidatorParams struct {

	/*WithdrawRequestBody*/
	WithdrawRequestBody WithdrawRewardsByValidatorBody
	/*DelegatorAddr
	  Bech32 AccAddress of Delegator

	*/
	DelegatorAddr string
	/*ValidatorAddr
	  Bech32 OperatorAddress of validator

	*/
	ValidatorAddr string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the withdraw rewards by validator params
func (o *WithdrawRewardsByValidatorParams) WithTimeout(timeout time.Duration) *WithdrawRewardsByValidatorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the withdraw rewards by validator params
func (o *WithdrawRewardsByValidatorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the withdraw rewards by validator params
func (o *WithdrawRewardsByValidatorParams) WithContext(ctx context.Context) *WithdrawRewardsByValidatorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the withdraw rewards by validator params
func (o *WithdrawRewardsByValidatorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the withdraw rewards by validator params
func (o *WithdrawRewardsByValidatorParams) WithHTTPClient(client *http.Client) *WithdrawRewardsByValidatorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the withdraw rewards by validator params
func (o *WithdrawRewardsByValidatorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWithdrawRequestBody adds the withdrawRequestBody to the withdraw rewards by validator params
func (o *WithdrawRewardsByValidatorParams) WithWithdrawRequestBody(withdrawRequestBody WithdrawRewardsByValidatorBody) *WithdrawRewardsByValidatorParams {
	o.SetWithdrawRequestBody(withdrawRequestBody)
	return o
}

// SetWithdrawRequestBody adds the withdrawRequestBody to the withdraw rewards by validator params
func (o *WithdrawRewardsByValidatorParams) SetWithdrawRequestBody(withdrawRequestBody WithdrawRewardsByValidatorBody) {
	o.WithdrawRequestBody = withdrawRequestBody
}

// WithDelegatorAddr adds the delegatorAddr to the withdraw rewards by validator params
func (o *WithdrawRewardsByValidatorParams) WithDelegatorAddr(delegatorAddr string) *WithdrawRewardsByValidatorParams {
	o.SetDelegatorAddr(delegatorAddr)
	return o
}

// SetDelegatorAddr adds the delegatorAddr to the withdraw rewards by validator params
func (o *WithdrawRewardsByValidatorParams) SetDelegatorAddr(delegatorAddr string) {
	o.DelegatorAddr = delegatorAddr
}

// WithValidatorAddr adds the validatorAddr to the withdraw rewards by validator params
func (o *WithdrawRewardsByValidatorParams) WithValidatorAddr(validatorAddr string) *WithdrawRewardsByValidatorParams {
	o.SetValidatorAddr(validatorAddr)
	return o
}

// SetValidatorAddr adds the validatorAddr to the withdraw rewards by validator params
func (o *WithdrawRewardsByValidatorParams) SetValidatorAddr(validatorAddr string) {
	o.ValidatorAddr = validatorAddr
}

// WriteToRequest writes these params to a swagger request
func (o *WithdrawRewardsByValidatorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.WithdrawRequestBody); err != nil {
		return err
	}

	// path param delegatorAddr
	if err := r.SetPathParam("delegatorAddr", o.DelegatorAddr); err != nil {
		return err
	}

	// path param validatorAddr
	if err := r.SetPathParam("validatorAddr", o.ValidatorAddr); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
