// Code generated by go-swagger; DO NOT EDIT.

package staking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUndelegationsOfDelegatorParams creates a new GetUndelegationsOfDelegatorParams object
// with the default values initialized.
func NewGetUndelegationsOfDelegatorParams() *GetUndelegationsOfDelegatorParams {
	var ()
	return &GetUndelegationsOfDelegatorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUndelegationsOfDelegatorParamsWithTimeout creates a new GetUndelegationsOfDelegatorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUndelegationsOfDelegatorParamsWithTimeout(timeout time.Duration) *GetUndelegationsOfDelegatorParams {
	var ()
	return &GetUndelegationsOfDelegatorParams{

		timeout: timeout,
	}
}

// NewGetUndelegationsOfDelegatorParamsWithContext creates a new GetUndelegationsOfDelegatorParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetUndelegationsOfDelegatorParamsWithContext(ctx context.Context) *GetUndelegationsOfDelegatorParams {
	var ()
	return &GetUndelegationsOfDelegatorParams{

		Context: ctx,
	}
}

// NewGetUndelegationsOfDelegatorParamsWithHTTPClient creates a new GetUndelegationsOfDelegatorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetUndelegationsOfDelegatorParamsWithHTTPClient(client *http.Client) *GetUndelegationsOfDelegatorParams {
	var ()
	return &GetUndelegationsOfDelegatorParams{
		HTTPClient: client,
	}
}

/*GetUndelegationsOfDelegatorParams contains all the parameters to send to the API endpoint
for the get undelegations of delegator operation typically these are written to a http.Request
*/
type GetUndelegationsOfDelegatorParams struct {

	/*DelegatorAddr
	  Bech32 AccAddress of Delegator

	*/
	DelegatorAddr string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get undelegations of delegator params
func (o *GetUndelegationsOfDelegatorParams) WithTimeout(timeout time.Duration) *GetUndelegationsOfDelegatorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get undelegations of delegator params
func (o *GetUndelegationsOfDelegatorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get undelegations of delegator params
func (o *GetUndelegationsOfDelegatorParams) WithContext(ctx context.Context) *GetUndelegationsOfDelegatorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get undelegations of delegator params
func (o *GetUndelegationsOfDelegatorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get undelegations of delegator params
func (o *GetUndelegationsOfDelegatorParams) WithHTTPClient(client *http.Client) *GetUndelegationsOfDelegatorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get undelegations of delegator params
func (o *GetUndelegationsOfDelegatorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDelegatorAddr adds the delegatorAddr to the get undelegations of delegator params
func (o *GetUndelegationsOfDelegatorParams) WithDelegatorAddr(delegatorAddr string) *GetUndelegationsOfDelegatorParams {
	o.SetDelegatorAddr(delegatorAddr)
	return o
}

// SetDelegatorAddr adds the delegatorAddr to the get undelegations of delegator params
func (o *GetUndelegationsOfDelegatorParams) SetDelegatorAddr(delegatorAddr string) {
	o.DelegatorAddr = delegatorAddr
}

// WriteToRequest writes these params to a swagger request
func (o *GetUndelegationsOfDelegatorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param delegatorAddr
	if err := r.SetPathParam("delegatorAddr", o.DelegatorAddr); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
