// Code generated by go-swagger; DO NOT EDIT.

package staking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetValidatorOfDelegatorParams creates a new GetValidatorOfDelegatorParams object
// with the default values initialized.
func NewGetValidatorOfDelegatorParams() *GetValidatorOfDelegatorParams {
	var ()
	return &GetValidatorOfDelegatorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetValidatorOfDelegatorParamsWithTimeout creates a new GetValidatorOfDelegatorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetValidatorOfDelegatorParamsWithTimeout(timeout time.Duration) *GetValidatorOfDelegatorParams {
	var ()
	return &GetValidatorOfDelegatorParams{

		timeout: timeout,
	}
}

// NewGetValidatorOfDelegatorParamsWithContext creates a new GetValidatorOfDelegatorParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetValidatorOfDelegatorParamsWithContext(ctx context.Context) *GetValidatorOfDelegatorParams {
	var ()
	return &GetValidatorOfDelegatorParams{

		Context: ctx,
	}
}

// NewGetValidatorOfDelegatorParamsWithHTTPClient creates a new GetValidatorOfDelegatorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetValidatorOfDelegatorParamsWithHTTPClient(client *http.Client) *GetValidatorOfDelegatorParams {
	var ()
	return &GetValidatorOfDelegatorParams{
		HTTPClient: client,
	}
}

/*GetValidatorOfDelegatorParams contains all the parameters to send to the API endpoint
for the get validator of delegator operation typically these are written to a http.Request
*/
type GetValidatorOfDelegatorParams struct {

	/*DelegatorAddr
	  Bech32 AccAddress of Delegator

	*/
	DelegatorAddr string
	/*ValidatorAddr
	  Bech32 ValAddress of Delegator

	*/
	ValidatorAddr string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get validator of delegator params
func (o *GetValidatorOfDelegatorParams) WithTimeout(timeout time.Duration) *GetValidatorOfDelegatorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get validator of delegator params
func (o *GetValidatorOfDelegatorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get validator of delegator params
func (o *GetValidatorOfDelegatorParams) WithContext(ctx context.Context) *GetValidatorOfDelegatorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get validator of delegator params
func (o *GetValidatorOfDelegatorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get validator of delegator params
func (o *GetValidatorOfDelegatorParams) WithHTTPClient(client *http.Client) *GetValidatorOfDelegatorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get validator of delegator params
func (o *GetValidatorOfDelegatorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDelegatorAddr adds the delegatorAddr to the get validator of delegator params
func (o *GetValidatorOfDelegatorParams) WithDelegatorAddr(delegatorAddr string) *GetValidatorOfDelegatorParams {
	o.SetDelegatorAddr(delegatorAddr)
	return o
}

// SetDelegatorAddr adds the delegatorAddr to the get validator of delegator params
func (o *GetValidatorOfDelegatorParams) SetDelegatorAddr(delegatorAddr string) {
	o.DelegatorAddr = delegatorAddr
}

// WithValidatorAddr adds the validatorAddr to the get validator of delegator params
func (o *GetValidatorOfDelegatorParams) WithValidatorAddr(validatorAddr string) *GetValidatorOfDelegatorParams {
	o.SetValidatorAddr(validatorAddr)
	return o
}

// SetValidatorAddr adds the validatorAddr to the get validator of delegator params
func (o *GetValidatorOfDelegatorParams) SetValidatorAddr(validatorAddr string) {
	o.ValidatorAddr = validatorAddr
}

// WriteToRequest writes these params to a swagger request
func (o *GetValidatorOfDelegatorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param delegatorAddr
	if err := r.SetPathParam("delegatorAddr", o.DelegatorAddr); err != nil {
		return err
	}

	// path param validatorAddr
	if err := r.SetPathParam("validatorAddr", o.ValidatorAddr); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
