// Code generated by go-swagger; DO NOT EDIT.

package market

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/coinexchain/dex-api-go/models"
)

// GetTradingPairReader is a Reader for the GetTradingPair structure.
type GetTradingPairReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTradingPairReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTradingPairOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetTradingPairBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetTradingPairInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTradingPairOK creates a GetTradingPairOK with default headers values
func NewGetTradingPairOK() *GetTradingPairOK {
	return &GetTradingPairOK{}
}

/*GetTradingPairOK handles this case with default header values.

trading-pair info of the specified symbol
*/
type GetTradingPairOK struct {
	Payload *GetTradingPairOKBody
}

func (o *GetTradingPairOK) Error() string {
	return fmt.Sprintf("[GET /market/trading-pairs/{stock}/{money}][%d] getTradingPairOK  %+v", 200, o.Payload)
}

func (o *GetTradingPairOK) GetPayload() *GetTradingPairOKBody {
	return o.Payload
}

func (o *GetTradingPairOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetTradingPairOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTradingPairBadRequest creates a GetTradingPairBadRequest with default headers values
func NewGetTradingPairBadRequest() *GetTradingPairBadRequest {
	return &GetTradingPairBadRequest{}
}

/*GetTradingPairBadRequest handles this case with default header values.

Invalid symbol
*/
type GetTradingPairBadRequest struct {
}

func (o *GetTradingPairBadRequest) Error() string {
	return fmt.Sprintf("[GET /market/trading-pairs/{stock}/{money}][%d] getTradingPairBadRequest ", 400)
}

func (o *GetTradingPairBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTradingPairInternalServerError creates a GetTradingPairInternalServerError with default headers values
func NewGetTradingPairInternalServerError() *GetTradingPairInternalServerError {
	return &GetTradingPairInternalServerError{}
}

/*GetTradingPairInternalServerError handles this case with default header values.

Server internal error
*/
type GetTradingPairInternalServerError struct {
}

func (o *GetTradingPairInternalServerError) Error() string {
	return fmt.Sprintf("[GET /market/trading-pairs/{stock}/{money}][%d] getTradingPairInternalServerError ", 500)
}

func (o *GetTradingPairInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetTradingPairOKBody get trading pair o k body
swagger:model GetTradingPairOKBody
*/
type GetTradingPairOKBody struct {

	// height
	Height string `json:"height,omitempty"`

	// result
	Result *models.MarketInfo `json:"result,omitempty"`
}

// Validate validates this get trading pair o k body
func (o *GetTradingPairOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetTradingPairOKBody) validateResult(formats strfmt.Registry) error {

	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getTradingPairOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetTradingPairOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetTradingPairOKBody) UnmarshalBinary(b []byte) error {
	var res GetTradingPairOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
