// Code generated by go-swagger; DO NOT EDIT.

package market

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/coinexchain/dex-api-go/models"
)

// ModifyPricePrecisionReader is a Reader for the ModifyPricePrecision structure.
type ModifyPricePrecisionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifyPricePrecisionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewModifyPricePrecisionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewModifyPricePrecisionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewModifyPricePrecisionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewModifyPricePrecisionOK creates a ModifyPricePrecisionOK with default headers values
func NewModifyPricePrecisionOK() *ModifyPricePrecisionOK {
	return &ModifyPricePrecisionOK{}
}

/*ModifyPricePrecisionOK handles this case with default header values.

Tx was succesfully generated
*/
type ModifyPricePrecisionOK struct {
	Payload *models.StdTx
}

func (o *ModifyPricePrecisionOK) Error() string {
	return fmt.Sprintf("[POST /market/price-precision][%d] modifyPricePrecisionOK  %+v", 200, o.Payload)
}

func (o *ModifyPricePrecisionOK) GetPayload() *models.StdTx {
	return o.Payload
}

func (o *ModifyPricePrecisionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StdTx)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewModifyPricePrecisionBadRequest creates a ModifyPricePrecisionBadRequest with default headers values
func NewModifyPricePrecisionBadRequest() *ModifyPricePrecisionBadRequest {
	return &ModifyPricePrecisionBadRequest{}
}

/*ModifyPricePrecisionBadRequest handles this case with default header values.

Invalid request
*/
type ModifyPricePrecisionBadRequest struct {
}

func (o *ModifyPricePrecisionBadRequest) Error() string {
	return fmt.Sprintf("[POST /market/price-precision][%d] modifyPricePrecisionBadRequest ", 400)
}

func (o *ModifyPricePrecisionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewModifyPricePrecisionInternalServerError creates a ModifyPricePrecisionInternalServerError with default headers values
func NewModifyPricePrecisionInternalServerError() *ModifyPricePrecisionInternalServerError {
	return &ModifyPricePrecisionInternalServerError{}
}

/*ModifyPricePrecisionInternalServerError handles this case with default header values.

Server internal error
*/
type ModifyPricePrecisionInternalServerError struct {
}

func (o *ModifyPricePrecisionInternalServerError) Error() string {
	return fmt.Sprintf("[POST /market/price-precision][%d] modifyPricePrecisionInternalServerError ", 500)
}

func (o *ModifyPricePrecisionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*ModifyPricePrecisionBody modify price precision body
swagger:model ModifyPricePrecisionBody
*/
type ModifyPricePrecisionBody struct {

	// base req
	BaseReq *models.BaseReq `json:"base_req,omitempty"`

	// price precision
	PricePrecision string `json:"price_precision,omitempty"`

	// trading pair
	TradingPair string `json:"trading_pair,omitempty"`
}

// Validate validates this modify price precision body
func (o *ModifyPricePrecisionBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBaseReq(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ModifyPricePrecisionBody) validateBaseReq(formats strfmt.Registry) error {

	if swag.IsZero(o.BaseReq) { // not required
		return nil
	}

	if o.BaseReq != nil {
		if err := o.BaseReq.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("info" + "." + "base_req")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ModifyPricePrecisionBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ModifyPricePrecisionBody) UnmarshalBinary(b []byte) error {
	var res ModifyPricePrecisionBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
