// Code generated by go-swagger; DO NOT EDIT.

package market

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewQueryDealParams creates a new QueryDealParams object
// with the default values initialized.
func NewQueryDealParams() *QueryDealParams {
	var ()
	return &QueryDealParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewQueryDealParamsWithTimeout creates a new QueryDealParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewQueryDealParamsWithTimeout(timeout time.Duration) *QueryDealParams {
	var ()
	return &QueryDealParams{

		timeout: timeout,
	}
}

// NewQueryDealParamsWithContext creates a new QueryDealParams object
// with the default values initialized, and the ability to set a context for a request
func NewQueryDealParamsWithContext(ctx context.Context) *QueryDealParams {
	var ()
	return &QueryDealParams{

		Context: ctx,
	}
}

// NewQueryDealParamsWithHTTPClient creates a new QueryDealParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewQueryDealParamsWithHTTPClient(client *http.Client) *QueryDealParams {
	var ()
	return &QueryDealParams{
		HTTPClient: client,
	}
}

/*QueryDealParams contains all the parameters to send to the API endpoint
for the query deal operation typically these are written to a http.Request
*/
type QueryDealParams struct {

	/*Count
	  Querier deal count limited to 1024

	*/
	Count int32
	/*Market
	  stock/money

	*/
	Market string
	/*Sid
	  Sequence id

	*/
	Sid int64
	/*Time
	  Unix timestamp

	*/
	Time int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the query deal params
func (o *QueryDealParams) WithTimeout(timeout time.Duration) *QueryDealParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the query deal params
func (o *QueryDealParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the query deal params
func (o *QueryDealParams) WithContext(ctx context.Context) *QueryDealParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the query deal params
func (o *QueryDealParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the query deal params
func (o *QueryDealParams) WithHTTPClient(client *http.Client) *QueryDealParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the query deal params
func (o *QueryDealParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCount adds the count to the query deal params
func (o *QueryDealParams) WithCount(count int32) *QueryDealParams {
	o.SetCount(count)
	return o
}

// SetCount adds the count to the query deal params
func (o *QueryDealParams) SetCount(count int32) {
	o.Count = count
}

// WithMarket adds the market to the query deal params
func (o *QueryDealParams) WithMarket(market string) *QueryDealParams {
	o.SetMarket(market)
	return o
}

// SetMarket adds the market to the query deal params
func (o *QueryDealParams) SetMarket(market string) {
	o.Market = market
}

// WithSid adds the sid to the query deal params
func (o *QueryDealParams) WithSid(sid int64) *QueryDealParams {
	o.SetSid(sid)
	return o
}

// SetSid adds the sid to the query deal params
func (o *QueryDealParams) SetSid(sid int64) {
	o.Sid = sid
}

// WithTime adds the time to the query deal params
func (o *QueryDealParams) WithTime(time int64) *QueryDealParams {
	o.SetTime(time)
	return o
}

// SetTime adds the time to the query deal params
func (o *QueryDealParams) SetTime(time int64) {
	o.Time = time
}

// WriteToRequest writes these params to a swagger request
func (o *QueryDealParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param count
	qrCount := o.Count
	qCount := swag.FormatInt32(qrCount)
	if qCount != "" {
		if err := r.SetQueryParam("count", qCount); err != nil {
			return err
		}
	}

	// query param market
	qrMarket := o.Market
	qMarket := qrMarket
	if qMarket != "" {
		if err := r.SetQueryParam("market", qMarket); err != nil {
			return err
		}
	}

	// query param sid
	qrSid := o.Sid
	qSid := swag.FormatInt64(qrSid)
	if qSid != "" {
		if err := r.SetQueryParam("sid", qSid); err != nil {
			return err
		}
	}

	// query param time
	qrTime := o.Time
	qTime := swag.FormatInt64(qrTime)
	if qTime != "" {
		if err := r.SetQueryParam("time", qTime); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
