// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/coinexchain/dex-api-go/models"
)

// NewAddWhitelistParams creates a new AddWhitelistParams object
// with the default values initialized.
func NewAddWhitelistParams() *AddWhitelistParams {
	var ()
	return &AddWhitelistParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddWhitelistParamsWithTimeout creates a new AddWhitelistParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddWhitelistParamsWithTimeout(timeout time.Duration) *AddWhitelistParams {
	var ()
	return &AddWhitelistParams{

		timeout: timeout,
	}
}

// NewAddWhitelistParamsWithContext creates a new AddWhitelistParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddWhitelistParamsWithContext(ctx context.Context) *AddWhitelistParams {
	var ()
	return &AddWhitelistParams{

		Context: ctx,
	}
}

// NewAddWhitelistParamsWithHTTPClient creates a new AddWhitelistParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddWhitelistParamsWithHTTPClient(client *http.Client) *AddWhitelistParams {
	var ()
	return &AddWhitelistParams{
		HTTPClient: client,
	}
}

/*AddWhitelistParams contains all the parameters to send to the API endpoint
for the add whitelist operation typically these are written to a http.Request
*/
type AddWhitelistParams struct {

	/*Symbol
	  token symbol

	*/
	Symbol string
	/*Whitelist
	  token whitelist addr

	*/
	Whitelist *models.Whitelist

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add whitelist params
func (o *AddWhitelistParams) WithTimeout(timeout time.Duration) *AddWhitelistParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add whitelist params
func (o *AddWhitelistParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add whitelist params
func (o *AddWhitelistParams) WithContext(ctx context.Context) *AddWhitelistParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add whitelist params
func (o *AddWhitelistParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add whitelist params
func (o *AddWhitelistParams) WithHTTPClient(client *http.Client) *AddWhitelistParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add whitelist params
func (o *AddWhitelistParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSymbol adds the symbol to the add whitelist params
func (o *AddWhitelistParams) WithSymbol(symbol string) *AddWhitelistParams {
	o.SetSymbol(symbol)
	return o
}

// SetSymbol adds the symbol to the add whitelist params
func (o *AddWhitelistParams) SetSymbol(symbol string) {
	o.Symbol = symbol
}

// WithWhitelist adds the whitelist to the add whitelist params
func (o *AddWhitelistParams) WithWhitelist(whitelist *models.Whitelist) *AddWhitelistParams {
	o.SetWhitelist(whitelist)
	return o
}

// SetWhitelist adds the whitelist to the add whitelist params
func (o *AddWhitelistParams) SetWhitelist(whitelist *models.Whitelist) {
	o.Whitelist = whitelist
}

// WriteToRequest writes these params to a swagger request
func (o *AddWhitelistParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param symbol
	if err := r.SetPathParam("symbol", o.Symbol); err != nil {
		return err
	}

	if o.Whitelist != nil {
		if err := r.SetBodyParam(o.Whitelist); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
