// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewBurnTokenParams creates a new BurnTokenParams object
// with the default values initialized.
func NewBurnTokenParams() *BurnTokenParams {
	var ()
	return &BurnTokenParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewBurnTokenParamsWithTimeout creates a new BurnTokenParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewBurnTokenParamsWithTimeout(timeout time.Duration) *BurnTokenParams {
	var ()
	return &BurnTokenParams{

		timeout: timeout,
	}
}

// NewBurnTokenParamsWithContext creates a new BurnTokenParams object
// with the default values initialized, and the ability to set a context for a request
func NewBurnTokenParamsWithContext(ctx context.Context) *BurnTokenParams {
	var ()
	return &BurnTokenParams{

		Context: ctx,
	}
}

// NewBurnTokenParamsWithHTTPClient creates a new BurnTokenParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewBurnTokenParamsWithHTTPClient(client *http.Client) *BurnTokenParams {
	var ()
	return &BurnTokenParams{
		HTTPClient: client,
	}
}

/*BurnTokenParams contains all the parameters to send to the API endpoint
for the burn token operation typically these are written to a http.Request
*/
type BurnTokenParams struct {

	/*Amount
	  burn token amount

	*/
	Amount BurnTokenBody
	/*Symbol
	  token symbol

	*/
	Symbol string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the burn token params
func (o *BurnTokenParams) WithTimeout(timeout time.Duration) *BurnTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the burn token params
func (o *BurnTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the burn token params
func (o *BurnTokenParams) WithContext(ctx context.Context) *BurnTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the burn token params
func (o *BurnTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the burn token params
func (o *BurnTokenParams) WithHTTPClient(client *http.Client) *BurnTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the burn token params
func (o *BurnTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAmount adds the amount to the burn token params
func (o *BurnTokenParams) WithAmount(amount BurnTokenBody) *BurnTokenParams {
	o.SetAmount(amount)
	return o
}

// SetAmount adds the amount to the burn token params
func (o *BurnTokenParams) SetAmount(amount BurnTokenBody) {
	o.Amount = amount
}

// WithSymbol adds the symbol to the burn token params
func (o *BurnTokenParams) WithSymbol(symbol string) *BurnTokenParams {
	o.SetSymbol(symbol)
	return o
}

// SetSymbol adds the symbol to the burn token params
func (o *BurnTokenParams) SetSymbol(symbol string) {
	o.Symbol = symbol
}

// WriteToRequest writes these params to a swagger request
func (o *BurnTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Amount); err != nil {
		return err
	}

	// path param symbol
	if err := r.SetPathParam("symbol", o.Symbol); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
