// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewForbidTokenParams creates a new ForbidTokenParams object
// with the default values initialized.
func NewForbidTokenParams() *ForbidTokenParams {
	var ()
	return &ForbidTokenParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewForbidTokenParamsWithTimeout creates a new ForbidTokenParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewForbidTokenParamsWithTimeout(timeout time.Duration) *ForbidTokenParams {
	var ()
	return &ForbidTokenParams{

		timeout: timeout,
	}
}

// NewForbidTokenParamsWithContext creates a new ForbidTokenParams object
// with the default values initialized, and the ability to set a context for a request
func NewForbidTokenParamsWithContext(ctx context.Context) *ForbidTokenParams {
	var ()
	return &ForbidTokenParams{

		Context: ctx,
	}
}

// NewForbidTokenParamsWithHTTPClient creates a new ForbidTokenParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewForbidTokenParamsWithHTTPClient(client *http.Client) *ForbidTokenParams {
	var ()
	return &ForbidTokenParams{
		HTTPClient: client,
	}
}

/*ForbidTokenParams contains all the parameters to send to the API endpoint
for the forbid token operation typically these are written to a http.Request
*/
type ForbidTokenParams struct {

	/*BaseReq
	  base req

	*/
	BaseReq ForbidTokenBody
	/*Symbol
	  token symbol

	*/
	Symbol string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the forbid token params
func (o *ForbidTokenParams) WithTimeout(timeout time.Duration) *ForbidTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the forbid token params
func (o *ForbidTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the forbid token params
func (o *ForbidTokenParams) WithContext(ctx context.Context) *ForbidTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the forbid token params
func (o *ForbidTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the forbid token params
func (o *ForbidTokenParams) WithHTTPClient(client *http.Client) *ForbidTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the forbid token params
func (o *ForbidTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBaseReq adds the baseReq to the forbid token params
func (o *ForbidTokenParams) WithBaseReq(baseReq ForbidTokenBody) *ForbidTokenParams {
	o.SetBaseReq(baseReq)
	return o
}

// SetBaseReq adds the baseReq to the forbid token params
func (o *ForbidTokenParams) SetBaseReq(baseReq ForbidTokenBody) {
	o.BaseReq = baseReq
}

// WithSymbol adds the symbol to the forbid token params
func (o *ForbidTokenParams) WithSymbol(symbol string) *ForbidTokenParams {
	o.SetSymbol(symbol)
	return o
}

// SetSymbol adds the symbol to the forbid token params
func (o *ForbidTokenParams) SetSymbol(symbol string) {
	o.Symbol = symbol
}

// WriteToRequest writes these params to a swagger request
func (o *ForbidTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.BaseReq); err != nil {
		return err
	}

	// path param symbol
	if err := r.SetPathParam("symbol", o.Symbol); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
