// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/coinexchain/dex-api-go/models"
)

// ForbidAddrReader is a Reader for the ForbidAddr structure.
type ForbidAddrReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ForbidAddrReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewForbidAddrOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewForbidAddrBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewForbidAddrInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewForbidAddrOK creates a ForbidAddrOK with default headers values
func NewForbidAddrOK() *ForbidAddrOK {
	return &ForbidAddrOK{}
}

/*ForbidAddrOK handles this case with default header values.

Forbid address result
*/
type ForbidAddrOK struct {
	Payload *models.StdTx
}

func (o *ForbidAddrOK) Error() string {
	return fmt.Sprintf("[POST /asset/tokens/{symbol}/forbidden/addresses][%d] forbidAddrOK  %+v", 200, o.Payload)
}

func (o *ForbidAddrOK) GetPayload() *models.StdTx {
	return o.Payload
}

func (o *ForbidAddrOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StdTx)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewForbidAddrBadRequest creates a ForbidAddrBadRequest with default headers values
func NewForbidAddrBadRequest() *ForbidAddrBadRequest {
	return &ForbidAddrBadRequest{}
}

/*ForbidAddrBadRequest handles this case with default header values.

Invalid Request
*/
type ForbidAddrBadRequest struct {
}

func (o *ForbidAddrBadRequest) Error() string {
	return fmt.Sprintf("[POST /asset/tokens/{symbol}/forbidden/addresses][%d] forbidAddrBadRequest ", 400)
}

func (o *ForbidAddrBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewForbidAddrInternalServerError creates a ForbidAddrInternalServerError with default headers values
func NewForbidAddrInternalServerError() *ForbidAddrInternalServerError {
	return &ForbidAddrInternalServerError{}
}

/*ForbidAddrInternalServerError handles this case with default header values.

Internal Server Error
*/
type ForbidAddrInternalServerError struct {
}

func (o *ForbidAddrInternalServerError) Error() string {
	return fmt.Sprintf("[POST /asset/tokens/{symbol}/forbidden/addresses][%d] forbidAddrInternalServerError ", 500)
}

func (o *ForbidAddrInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
