// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetReservedSymbolsParams creates a new GetReservedSymbolsParams object
// with the default values initialized.
func NewGetReservedSymbolsParams() *GetReservedSymbolsParams {

	return &GetReservedSymbolsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetReservedSymbolsParamsWithTimeout creates a new GetReservedSymbolsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetReservedSymbolsParamsWithTimeout(timeout time.Duration) *GetReservedSymbolsParams {

	return &GetReservedSymbolsParams{

		timeout: timeout,
	}
}

// NewGetReservedSymbolsParamsWithContext creates a new GetReservedSymbolsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetReservedSymbolsParamsWithContext(ctx context.Context) *GetReservedSymbolsParams {

	return &GetReservedSymbolsParams{

		Context: ctx,
	}
}

// NewGetReservedSymbolsParamsWithHTTPClient creates a new GetReservedSymbolsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetReservedSymbolsParamsWithHTTPClient(client *http.Client) *GetReservedSymbolsParams {

	return &GetReservedSymbolsParams{
		HTTPClient: client,
	}
}

/*GetReservedSymbolsParams contains all the parameters to send to the API endpoint
for the get reserved symbols operation typically these are written to a http.Request
*/
type GetReservedSymbolsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get reserved symbols params
func (o *GetReservedSymbolsParams) WithTimeout(timeout time.Duration) *GetReservedSymbolsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get reserved symbols params
func (o *GetReservedSymbolsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get reserved symbols params
func (o *GetReservedSymbolsParams) WithContext(ctx context.Context) *GetReservedSymbolsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get reserved symbols params
func (o *GetReservedSymbolsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get reserved symbols params
func (o *GetReservedSymbolsParams) WithHTTPClient(client *http.Client) *GetReservedSymbolsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get reserved symbols params
func (o *GetReservedSymbolsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetReservedSymbolsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
