// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTokenListParams creates a new GetTokenListParams object
// with the default values initialized.
func NewGetTokenListParams() *GetTokenListParams {

	return &GetTokenListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTokenListParamsWithTimeout creates a new GetTokenListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTokenListParamsWithTimeout(timeout time.Duration) *GetTokenListParams {

	return &GetTokenListParams{

		timeout: timeout,
	}
}

// NewGetTokenListParamsWithContext creates a new GetTokenListParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTokenListParamsWithContext(ctx context.Context) *GetTokenListParams {

	return &GetTokenListParams{

		Context: ctx,
	}
}

// NewGetTokenListParamsWithHTTPClient creates a new GetTokenListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTokenListParamsWithHTTPClient(client *http.Client) *GetTokenListParams {

	return &GetTokenListParams{
		HTTPClient: client,
	}
}

/*GetTokenListParams contains all the parameters to send to the API endpoint
for the get token list operation typically these are written to a http.Request
*/
type GetTokenListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get token list params
func (o *GetTokenListParams) WithTimeout(timeout time.Duration) *GetTokenListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get token list params
func (o *GetTokenListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get token list params
func (o *GetTokenListParams) WithContext(ctx context.Context) *GetTokenListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get token list params
func (o *GetTokenListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get token list params
func (o *GetTokenListParams) WithHTTPClient(client *http.Client) *GetTokenListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get token list params
func (o *GetTokenListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetTokenListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
