// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetWhitelistParams creates a new GetWhitelistParams object
// with the default values initialized.
func NewGetWhitelistParams() *GetWhitelistParams {
	var ()
	return &GetWhitelistParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWhitelistParamsWithTimeout creates a new GetWhitelistParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWhitelistParamsWithTimeout(timeout time.Duration) *GetWhitelistParams {
	var ()
	return &GetWhitelistParams{

		timeout: timeout,
	}
}

// NewGetWhitelistParamsWithContext creates a new GetWhitelistParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetWhitelistParamsWithContext(ctx context.Context) *GetWhitelistParams {
	var ()
	return &GetWhitelistParams{

		Context: ctx,
	}
}

// NewGetWhitelistParamsWithHTTPClient creates a new GetWhitelistParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetWhitelistParamsWithHTTPClient(client *http.Client) *GetWhitelistParams {
	var ()
	return &GetWhitelistParams{
		HTTPClient: client,
	}
}

/*GetWhitelistParams contains all the parameters to send to the API endpoint
for the get whitelist operation typically these are written to a http.Request
*/
type GetWhitelistParams struct {

	/*Symbol
	  token symbol

	*/
	Symbol string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get whitelist params
func (o *GetWhitelistParams) WithTimeout(timeout time.Duration) *GetWhitelistParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get whitelist params
func (o *GetWhitelistParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get whitelist params
func (o *GetWhitelistParams) WithContext(ctx context.Context) *GetWhitelistParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get whitelist params
func (o *GetWhitelistParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get whitelist params
func (o *GetWhitelistParams) WithHTTPClient(client *http.Client) *GetWhitelistParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get whitelist params
func (o *GetWhitelistParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSymbol adds the symbol to the get whitelist params
func (o *GetWhitelistParams) WithSymbol(symbol string) *GetWhitelistParams {
	o.SetSymbol(symbol)
	return o
}

// SetSymbol adds the symbol to the get whitelist params
func (o *GetWhitelistParams) SetSymbol(symbol string) {
	o.Symbol = symbol
}

// WriteToRequest writes these params to a swagger request
func (o *GetWhitelistParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param symbol
	if err := r.SetPathParam("symbol", o.Symbol); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
