// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewTransferOwnershipParams creates a new TransferOwnershipParams object
// with the default values initialized.
func NewTransferOwnershipParams() *TransferOwnershipParams {
	var ()
	return &TransferOwnershipParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTransferOwnershipParamsWithTimeout creates a new TransferOwnershipParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTransferOwnershipParamsWithTimeout(timeout time.Duration) *TransferOwnershipParams {
	var ()
	return &TransferOwnershipParams{

		timeout: timeout,
	}
}

// NewTransferOwnershipParamsWithContext creates a new TransferOwnershipParams object
// with the default values initialized, and the ability to set a context for a request
func NewTransferOwnershipParamsWithContext(ctx context.Context) *TransferOwnershipParams {
	var ()
	return &TransferOwnershipParams{

		Context: ctx,
	}
}

// NewTransferOwnershipParamsWithHTTPClient creates a new TransferOwnershipParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTransferOwnershipParamsWithHTTPClient(client *http.Client) *TransferOwnershipParams {
	var ()
	return &TransferOwnershipParams{
		HTTPClient: client,
	}
}

/*TransferOwnershipParams contains all the parameters to send to the API endpoint
for the transfer ownership operation typically these are written to a http.Request
*/
type TransferOwnershipParams struct {

	/*NewOwner
	  transfer ownership to new owner

	*/
	NewOwner TransferOwnershipBody
	/*Symbol
	  token symbol

	*/
	Symbol string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the transfer ownership params
func (o *TransferOwnershipParams) WithTimeout(timeout time.Duration) *TransferOwnershipParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the transfer ownership params
func (o *TransferOwnershipParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the transfer ownership params
func (o *TransferOwnershipParams) WithContext(ctx context.Context) *TransferOwnershipParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the transfer ownership params
func (o *TransferOwnershipParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the transfer ownership params
func (o *TransferOwnershipParams) WithHTTPClient(client *http.Client) *TransferOwnershipParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the transfer ownership params
func (o *TransferOwnershipParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNewOwner adds the newOwner to the transfer ownership params
func (o *TransferOwnershipParams) WithNewOwner(newOwner TransferOwnershipBody) *TransferOwnershipParams {
	o.SetNewOwner(newOwner)
	return o
}

// SetNewOwner adds the newOwner to the transfer ownership params
func (o *TransferOwnershipParams) SetNewOwner(newOwner TransferOwnershipBody) {
	o.NewOwner = newOwner
}

// WithSymbol adds the symbol to the transfer ownership params
func (o *TransferOwnershipParams) WithSymbol(symbol string) *TransferOwnershipParams {
	o.SetSymbol(symbol)
	return o
}

// SetSymbol adds the symbol to the transfer ownership params
func (o *TransferOwnershipParams) SetSymbol(symbol string) {
	o.Symbol = symbol
}

// WriteToRequest writes these params to a swagger request
func (o *TransferOwnershipParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.NewOwner); err != nil {
		return err
	}

	// path param symbol
	if err := r.SetPathParam("symbol", o.Symbol); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
