// Code generated by go-swagger; DO NOT EDIT.

package asset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/coinexchain/dex-api-go/models"
)

// NewUnForbidAddrParams creates a new UnForbidAddrParams object
// with the default values initialized.
func NewUnForbidAddrParams() *UnForbidAddrParams {
	var ()
	return &UnForbidAddrParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUnForbidAddrParamsWithTimeout creates a new UnForbidAddrParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUnForbidAddrParamsWithTimeout(timeout time.Duration) *UnForbidAddrParams {
	var ()
	return &UnForbidAddrParams{

		timeout: timeout,
	}
}

// NewUnForbidAddrParamsWithContext creates a new UnForbidAddrParams object
// with the default values initialized, and the ability to set a context for a request
func NewUnForbidAddrParamsWithContext(ctx context.Context) *UnForbidAddrParams {
	var ()
	return &UnForbidAddrParams{

		Context: ctx,
	}
}

// NewUnForbidAddrParamsWithHTTPClient creates a new UnForbidAddrParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUnForbidAddrParamsWithHTTPClient(client *http.Client) *UnForbidAddrParams {
	var ()
	return &UnForbidAddrParams{
		HTTPClient: client,
	}
}

/*UnForbidAddrParams contains all the parameters to send to the API endpoint
for the un forbid addr operation typically these are written to a http.Request
*/
type UnForbidAddrParams struct {

	/*Addresses
	  un forbidden addresses

	*/
	Addresses *models.Addresses
	/*Symbol
	  token symbol

	*/
	Symbol string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the un forbid addr params
func (o *UnForbidAddrParams) WithTimeout(timeout time.Duration) *UnForbidAddrParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the un forbid addr params
func (o *UnForbidAddrParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the un forbid addr params
func (o *UnForbidAddrParams) WithContext(ctx context.Context) *UnForbidAddrParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the un forbid addr params
func (o *UnForbidAddrParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the un forbid addr params
func (o *UnForbidAddrParams) WithHTTPClient(client *http.Client) *UnForbidAddrParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the un forbid addr params
func (o *UnForbidAddrParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddresses adds the addresses to the un forbid addr params
func (o *UnForbidAddrParams) WithAddresses(addresses *models.Addresses) *UnForbidAddrParams {
	o.SetAddresses(addresses)
	return o
}

// SetAddresses adds the addresses to the un forbid addr params
func (o *UnForbidAddrParams) SetAddresses(addresses *models.Addresses) {
	o.Addresses = addresses
}

// WithSymbol adds the symbol to the un forbid addr params
func (o *UnForbidAddrParams) WithSymbol(symbol string) *UnForbidAddrParams {
	o.SetSymbol(symbol)
	return o
}

// SetSymbol adds the symbol to the un forbid addr params
func (o *UnForbidAddrParams) SetSymbol(symbol string) {
	o.Symbol = symbol
}

// WriteToRequest writes these params to a swagger request
func (o *UnForbidAddrParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Addresses != nil {
		if err := r.SetBodyParam(o.Addresses); err != nil {
			return err
		}
	}

	// path param symbol
	if err := r.SetPathParam("symbol", o.Symbol); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
