// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAuthParamsParams creates a new GetAuthParamsParams object
// with the default values initialized.
func NewGetAuthParamsParams() *GetAuthParamsParams {

	return &GetAuthParamsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAuthParamsParamsWithTimeout creates a new GetAuthParamsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAuthParamsParamsWithTimeout(timeout time.Duration) *GetAuthParamsParams {

	return &GetAuthParamsParams{

		timeout: timeout,
	}
}

// NewGetAuthParamsParamsWithContext creates a new GetAuthParamsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAuthParamsParamsWithContext(ctx context.Context) *GetAuthParamsParams {

	return &GetAuthParamsParams{

		Context: ctx,
	}
}

// NewGetAuthParamsParamsWithHTTPClient creates a new GetAuthParamsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAuthParamsParamsWithHTTPClient(client *http.Client) *GetAuthParamsParams {

	return &GetAuthParamsParams{
		HTTPClient: client,
	}
}

/*GetAuthParamsParams contains all the parameters to send to the API endpoint
for the get auth params operation typically these are written to a http.Request
*/
type GetAuthParamsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get auth params params
func (o *GetAuthParamsParams) WithTimeout(timeout time.Duration) *GetAuthParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get auth params params
func (o *GetAuthParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get auth params params
func (o *GetAuthParamsParams) WithContext(ctx context.Context) *GetAuthParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get auth params params
func (o *GetAuthParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get auth params params
func (o *GetAuthParamsParams) WithHTTPClient(client *http.Client) *GetAuthParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get auth params params
func (o *GetAuthParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAuthParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
