// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetAuthParamsReader is a Reader for the GetAuthParams structure.
type GetAuthParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAuthParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAuthParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetAuthParamsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAuthParamsOK creates a GetAuthParamsOK with default headers values
func NewGetAuthParamsOK() *GetAuthParamsOK {
	return &GetAuthParamsOK{}
}

/*GetAuthParamsOK handles this case with default header values.

OK
*/
type GetAuthParamsOK struct {
	Payload *GetAuthParamsOKBody
}

func (o *GetAuthParamsOK) Error() string {
	return fmt.Sprintf("[GET /auth/parameters][%d] getAuthParamsOK  %+v", 200, o.Payload)
}

func (o *GetAuthParamsOK) GetPayload() *GetAuthParamsOKBody {
	return o.Payload
}

func (o *GetAuthParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetAuthParamsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAuthParamsInternalServerError creates a GetAuthParamsInternalServerError with default headers values
func NewGetAuthParamsInternalServerError() *GetAuthParamsInternalServerError {
	return &GetAuthParamsInternalServerError{}
}

/*GetAuthParamsInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetAuthParamsInternalServerError struct {
}

func (o *GetAuthParamsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /auth/parameters][%d] getAuthParamsInternalServerError ", 500)
}

func (o *GetAuthParamsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetAuthParamsOKBody get auth params o k body
swagger:model GetAuthParamsOKBody
*/
type GetAuthParamsOKBody struct {

	// height
	Height string `json:"height,omitempty"`

	// result
	Result *GetAuthParamsOKBodyResult `json:"result,omitempty"`
}

// Validate validates this get auth params o k body
func (o *GetAuthParamsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetAuthParamsOKBody) validateResult(formats strfmt.Registry) error {

	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getAuthParamsOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetAuthParamsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAuthParamsOKBody) UnmarshalBinary(b []byte) error {
	var res GetAuthParamsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetAuthParamsOKBodyResult get auth params o k body result
swagger:model GetAuthParamsOKBodyResult
*/
type GetAuthParamsOKBodyResult struct {

	// max memo characters
	MaxMemoCharacters string `json:"max_memo_characters,omitempty"`

	// min gas price limit
	MinGasPriceLimit string `json:"min_gas_price_limit,omitempty"`

	// sig verify cost ed25519
	SigVerifyCostEd25519 string `json:"sig_verify_cost_ed25519,omitempty"`

	// sig verify cost secp256k1
	SigVerifyCostSecp256k1 string `json:"sig_verify_cost_secp256k1,omitempty"`

	// tx sig limit
	TxSigLimit string `json:"tx_sig_limit,omitempty"`

	// tx size cost per byte
	TxSizeCostPerByte string `json:"tx_size_cost_per_byte,omitempty"`
}

// Validate validates this get auth params o k body result
func (o *GetAuthParamsOKBodyResult) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAuthParamsOKBodyResult) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAuthParamsOKBodyResult) UnmarshalBinary(b []byte) error {
	var res GetAuthParamsOKBodyResult
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
