// Code generated by go-swagger; DO NOT EDIT.

package bancorlite

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBancorliteParamsParams creates a new GetBancorliteParamsParams object
// with the default values initialized.
func NewGetBancorliteParamsParams() *GetBancorliteParamsParams {

	return &GetBancorliteParamsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBancorliteParamsParamsWithTimeout creates a new GetBancorliteParamsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBancorliteParamsParamsWithTimeout(timeout time.Duration) *GetBancorliteParamsParams {

	return &GetBancorliteParamsParams{

		timeout: timeout,
	}
}

// NewGetBancorliteParamsParamsWithContext creates a new GetBancorliteParamsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBancorliteParamsParamsWithContext(ctx context.Context) *GetBancorliteParamsParams {

	return &GetBancorliteParamsParams{

		Context: ctx,
	}
}

// NewGetBancorliteParamsParamsWithHTTPClient creates a new GetBancorliteParamsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBancorliteParamsParamsWithHTTPClient(client *http.Client) *GetBancorliteParamsParams {

	return &GetBancorliteParamsParams{
		HTTPClient: client,
	}
}

/*GetBancorliteParamsParams contains all the parameters to send to the API endpoint
for the get bancorlite params operation typically these are written to a http.Request
*/
type GetBancorliteParamsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get bancorlite params params
func (o *GetBancorliteParamsParams) WithTimeout(timeout time.Duration) *GetBancorliteParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get bancorlite params params
func (o *GetBancorliteParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get bancorlite params params
func (o *GetBancorliteParamsParams) WithContext(ctx context.Context) *GetBancorliteParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get bancorlite params params
func (o *GetBancorliteParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get bancorlite params params
func (o *GetBancorliteParamsParams) WithHTTPClient(client *http.Client) *GetBancorliteParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get bancorlite params params
func (o *GetBancorliteParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetBancorliteParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
