// Code generated by go-swagger; DO NOT EDIT.

package bancorlite

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBancorInfosParams creates a new GetBancorInfosParams object
// with the default values initialized.
func NewGetBancorInfosParams() *GetBancorInfosParams {

	return &GetBancorInfosParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBancorInfosParamsWithTimeout creates a new GetBancorInfosParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBancorInfosParamsWithTimeout(timeout time.Duration) *GetBancorInfosParams {

	return &GetBancorInfosParams{

		timeout: timeout,
	}
}

// NewGetBancorInfosParamsWithContext creates a new GetBancorInfosParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBancorInfosParamsWithContext(ctx context.Context) *GetBancorInfosParams {

	return &GetBancorInfosParams{

		Context: ctx,
	}
}

// NewGetBancorInfosParamsWithHTTPClient creates a new GetBancorInfosParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBancorInfosParamsWithHTTPClient(client *http.Client) *GetBancorInfosParams {

	return &GetBancorInfosParams{
		HTTPClient: client,
	}
}

/*GetBancorInfosParams contains all the parameters to send to the API endpoint
for the get bancor infos operation typically these are written to a http.Request
*/
type GetBancorInfosParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get bancor infos params
func (o *GetBancorInfosParams) WithTimeout(timeout time.Duration) *GetBancorInfosParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get bancor infos params
func (o *GetBancorInfosParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get bancor infos params
func (o *GetBancorInfosParams) WithContext(ctx context.Context) *GetBancorInfosParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get bancor infos params
func (o *GetBancorInfosParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get bancor infos params
func (o *GetBancorInfosParams) WithHTTPClient(client *http.Client) *GetBancorInfosParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get bancor infos params
func (o *GetBancorInfosParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetBancorInfosParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
