// Code generated by go-swagger; DO NOT EDIT.

package bancorlite

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetBancorliteParamsReader is a Reader for the GetBancorliteParams structure.
type GetBancorliteParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBancorliteParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBancorliteParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetBancorliteParamsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetBancorliteParamsOK creates a GetBancorliteParamsOK with default headers values
func NewGetBancorliteParamsOK() *GetBancorliteParamsOK {
	return &GetBancorliteParamsOK{}
}

/*GetBancorliteParamsOK handles this case with default header values.

OK
*/
type GetBancorliteParamsOK struct {
	Payload *GetBancorliteParamsOKBody
}

func (o *GetBancorliteParamsOK) Error() string {
	return fmt.Sprintf("[GET /bancorlite/parameters][%d] getBancorliteParamsOK  %+v", 200, o.Payload)
}

func (o *GetBancorliteParamsOK) GetPayload() *GetBancorliteParamsOKBody {
	return o.Payload
}

func (o *GetBancorliteParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetBancorliteParamsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBancorliteParamsInternalServerError creates a GetBancorliteParamsInternalServerError with default headers values
func NewGetBancorliteParamsInternalServerError() *GetBancorliteParamsInternalServerError {
	return &GetBancorliteParamsInternalServerError{}
}

/*GetBancorliteParamsInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetBancorliteParamsInternalServerError struct {
}

func (o *GetBancorliteParamsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /bancorlite/parameters][%d] getBancorliteParamsInternalServerError ", 500)
}

func (o *GetBancorliteParamsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetBancorliteParamsOKBody get bancorlite params o k body
swagger:model GetBancorliteParamsOKBody
*/
type GetBancorliteParamsOKBody struct {

	// height
	Height string `json:"height,omitempty"`

	// result
	Result *GetBancorliteParamsOKBodyResult `json:"result,omitempty"`
}

// Validate validates this get bancorlite params o k body
func (o *GetBancorliteParamsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetBancorliteParamsOKBody) validateResult(formats strfmt.Registry) error {

	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getBancorliteParamsOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetBancorliteParamsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetBancorliteParamsOKBody) UnmarshalBinary(b []byte) error {
	var res GetBancorliteParamsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetBancorliteParamsOKBodyResult get bancorlite params o k body result
swagger:model GetBancorliteParamsOKBodyResult
*/
type GetBancorliteParamsOKBodyResult struct {

	// cancel bancor fee
	CancelBancorFee string `json:"cancel_bancor_fee,omitempty"`

	// create bancor fee
	CreateBancorFee string `json:"create_bancor_fee,omitempty"`

	// trade fee rate
	TradeFeeRate string `json:"trade_fee_rate,omitempty"`
}

// Validate validates this get bancorlite params o k body result
func (o *GetBancorliteParamsOKBodyResult) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetBancorliteParamsOKBodyResult) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetBancorliteParamsOKBodyResult) UnmarshalBinary(b []byte) error {
	var res GetBancorliteParamsOKBodyResult
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
