// Code generated by go-swagger; DO NOT EDIT.

package expiry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewQueryUnlockParams creates a new QueryUnlockParams object
// with the default values initialized.
func NewQueryUnlockParams() *QueryUnlockParams {
	var ()
	return &QueryUnlockParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewQueryUnlockParamsWithTimeout creates a new QueryUnlockParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewQueryUnlockParamsWithTimeout(timeout time.Duration) *QueryUnlockParams {
	var ()
	return &QueryUnlockParams{

		timeout: timeout,
	}
}

// NewQueryUnlockParamsWithContext creates a new QueryUnlockParams object
// with the default values initialized, and the ability to set a context for a request
func NewQueryUnlockParamsWithContext(ctx context.Context) *QueryUnlockParams {
	var ()
	return &QueryUnlockParams{

		Context: ctx,
	}
}

// NewQueryUnlockParamsWithHTTPClient creates a new QueryUnlockParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewQueryUnlockParamsWithHTTPClient(client *http.Client) *QueryUnlockParams {
	var ()
	return &QueryUnlockParams{
		HTTPClient: client,
	}
}

/*QueryUnlockParams contains all the parameters to send to the API endpoint
for the query unlock operation typically these are written to a http.Request
*/
type QueryUnlockParams struct {

	/*Account
	  Bech32 address

	*/
	Account string
	/*Count
	  Querier count

	*/
	Count int32
	/*Sid
	  Sequence id

	*/
	Sid int64
	/*Time
	  Unix timestamp

	*/
	Time int64
	/*Token
	  Symbol

	*/
	Token *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the query unlock params
func (o *QueryUnlockParams) WithTimeout(timeout time.Duration) *QueryUnlockParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the query unlock params
func (o *QueryUnlockParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the query unlock params
func (o *QueryUnlockParams) WithContext(ctx context.Context) *QueryUnlockParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the query unlock params
func (o *QueryUnlockParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the query unlock params
func (o *QueryUnlockParams) WithHTTPClient(client *http.Client) *QueryUnlockParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the query unlock params
func (o *QueryUnlockParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccount adds the account to the query unlock params
func (o *QueryUnlockParams) WithAccount(account string) *QueryUnlockParams {
	o.SetAccount(account)
	return o
}

// SetAccount adds the account to the query unlock params
func (o *QueryUnlockParams) SetAccount(account string) {
	o.Account = account
}

// WithCount adds the count to the query unlock params
func (o *QueryUnlockParams) WithCount(count int32) *QueryUnlockParams {
	o.SetCount(count)
	return o
}

// SetCount adds the count to the query unlock params
func (o *QueryUnlockParams) SetCount(count int32) {
	o.Count = count
}

// WithSid adds the sid to the query unlock params
func (o *QueryUnlockParams) WithSid(sid int64) *QueryUnlockParams {
	o.SetSid(sid)
	return o
}

// SetSid adds the sid to the query unlock params
func (o *QueryUnlockParams) SetSid(sid int64) {
	o.Sid = sid
}

// WithTime adds the time to the query unlock params
func (o *QueryUnlockParams) WithTime(time int64) *QueryUnlockParams {
	o.SetTime(time)
	return o
}

// SetTime adds the time to the query unlock params
func (o *QueryUnlockParams) SetTime(time int64) {
	o.Time = time
}

// WithToken adds the token to the query unlock params
func (o *QueryUnlockParams) WithToken(token *string) *QueryUnlockParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the query unlock params
func (o *QueryUnlockParams) SetToken(token *string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *QueryUnlockParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param account
	qrAccount := o.Account
	qAccount := qrAccount
	if qAccount != "" {
		if err := r.SetQueryParam("account", qAccount); err != nil {
			return err
		}
	}

	// query param count
	qrCount := o.Count
	qCount := swag.FormatInt32(qrCount)
	if qCount != "" {
		if err := r.SetQueryParam("count", qCount); err != nil {
			return err
		}
	}

	// query param sid
	qrSid := o.Sid
	qSid := swag.FormatInt64(qrSid)
	if qSid != "" {
		if err := r.SetQueryParam("sid", qSid); err != nil {
			return err
		}
	}

	// query param time
	qrTime := o.Time
	qTime := swag.FormatInt64(qrTime)
	if qTime != "" {
		if err := r.SetQueryParam("time", qTime); err != nil {
			return err
		}
	}

	if o.Token != nil {

		// query param token
		var qrToken string
		if o.Token != nil {
			qrToken = *o.Token
		}
		qToken := qrToken
		if qToken != "" {
			if err := r.SetQueryParam("token", qToken); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
