// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DelegationDelegatorReward delegation delegator reward
//
// swagger:model DelegationDelegatorReward
type DelegationDelegatorReward struct {

	// reward
	// Required: true
	Reward []*Coin `json:"reward"`

	// validator address
	// Required: true
	ValidatorAddress ValidatorAddress `json:"validator_address"`
}

// Validate validates this delegation delegator reward
func (m *DelegationDelegatorReward) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReward(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValidatorAddress(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DelegationDelegatorReward) validateReward(formats strfmt.Registry) error {

	if err := validate.Required("reward", "body", m.Reward); err != nil {
		return err
	}

	for i := 0; i < len(m.Reward); i++ {
		if swag.IsZero(m.Reward[i]) { // not required
			continue
		}

		if m.Reward[i] != nil {
			if err := m.Reward[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("reward" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *DelegationDelegatorReward) validateValidatorAddress(formats strfmt.Registry) error {

	if err := m.ValidatorAddress.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("validator_address")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DelegationDelegatorReward) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DelegationDelegatorReward) UnmarshalBinary(b []byte) error {
	var res DelegationDelegatorReward
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
