// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Proposer proposer
//
// swagger:model Proposer
type Proposer struct {

	// proposal id
	// Required: true
	ProposalID *string `json:"proposal_id"`

	// proposer
	// Required: true
	Proposer *string `json:"proposer"`
}

// Validate validates this proposer
func (m *Proposer) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProposalID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProposer(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Proposer) validateProposalID(formats strfmt.Registry) error {

	if err := validate.Required("proposal_id", "body", m.ProposalID); err != nil {
		return err
	}

	return nil
}

func (m *Proposer) validateProposer(formats strfmt.Registry) error {

	if err := validate.Required("proposer", "body", m.Proposer); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Proposer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Proposer) UnmarshalBinary(b []byte) error {
	var res Proposer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
