// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TendermintValidator tendermint validator
//
// swagger:model TendermintValidator
type TendermintValidator struct {

	// address
	// Required: true
	Address ValidatorAddress `json:"address"`

	// proposer priority
	// Required: true
	ProposerPriority *string `json:"proposer_priority"`

	// pub key
	// Required: true
	PubKey *string `json:"pub_key"`

	// voting power
	// Required: true
	VotingPower *string `json:"voting_power"`
}

// Validate validates this tendermint validator
func (m *TendermintValidator) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProposerPriority(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePubKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVotingPower(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TendermintValidator) validateAddress(formats strfmt.Registry) error {

	if err := m.Address.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("address")
		}
		return err
	}

	return nil
}

func (m *TendermintValidator) validateProposerPriority(formats strfmt.Registry) error {

	if err := validate.Required("proposer_priority", "body", m.ProposerPriority); err != nil {
		return err
	}

	return nil
}

func (m *TendermintValidator) validatePubKey(formats strfmt.Registry) error {

	if err := validate.Required("pub_key", "body", m.PubKey); err != nil {
		return err
	}

	return nil
}

func (m *TendermintValidator) validateVotingPower(formats strfmt.Registry) error {

	if err := validate.Required("voting_power", "body", m.VotingPower); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TendermintValidator) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TendermintValidator) UnmarshalBinary(b []byte) error {
	var res TendermintValidator
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
