// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Tickers tickers
//
// swagger:model Tickers
type Tickers struct {

	// market
	Market string `json:"market,omitempty"`

	// Newest price
	New string `json:"new,omitempty"`

	// Old price one day ago
	Old string `json:"old,omitempty"`
}

// Validate validates this tickers
func (m *Tickers) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Tickers) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Tickers) UnmarshalBinary(b []byte) error {
	var res Tickers
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
